---
title: "QC_2025_09_v3.2.2_Cuklina_proBatch"
output: html_document
---

Overview

<https://rdrr.io/bioc/proBatch/f/README.md><https://rdrr.io/bioc/proBatch/>

Purpose & Comparisons -

Data used

Based off of

Links

1.  [Mastering File Manipulation with R’s list.files() Function](https://www.r-bloggers.com/2023/05/mastering-file-manipulation-with-rs-list-files-function/)
2.  [Reading Data from multiple files](https://www.r-bloggers.com/2023/05/mastering-file-manipulation-with-rs-list-files-function/)

```{r}
# Does not work
# Error: Failed to install 'proBatch' from GitHub:
#   ! System command 'R' failed

# too old? was removed from BioConductor?

# install.packages('devtools') 
# devtools::install_github('symbioticMe/proBatch', build_vignettes = TRUE)
```

Load Packages

```{r}
library(readr) # read csv files read_csv
library(readxl) # read in excel files read_excel
library(tidyr) # pivot longer
library(stringr) # str_detect()
library(dplyr)
library(ggh4x) # facet_nested - extensions of facet_grid for nesting
library(cowplot) # for plot_grid()
library(gt)
library(ggridges)
library(forcats) #fct_rev
library(purrr) # for map()
library(ggvenn) #for ggvenn
library(paletteer) # color palette
library(ggExtra) # fpr ggMarginal
```

Load Data

PSMs

```{r}
#set_wd to sourcefile location
#input_dir <- "input/PD/"
# dirs <- list.dirs(input_dir) # lists directories | not needed 

PSMs_2_read <-  list.files(
  "input/PD/2025_08_Steph_TMTpro_PSMs_MSstatsTMT_EEvsSH_for_PhD", # where 2 read from
                       pattern = ".*PSM.*\\.txt$", # pattern PSM & ends .txt
                       full.names = TRUE, # get full name including path
                       recursive = TRUE) # gets files in subdirectories too


PD_PSMs <- read_tsv(PSMs_2_read, # read all files from list above
                    id = "file_path") # keep file path as an id column

# dim(PD_PSMs) #3658257 x 55
```

Input files

```{r}
input_files <- 


```
