---
title: "BioIn_2026_01_v3.4.2_ClusterProfiler_EExAge_vis_v2"
author: "Stephanie Huang"
date: "2026-01-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# [BioIn_2026_01_v3.4.2_ClusterProfiler_EExAge_vis_v2]{.underline}

# Setup

### Load Packages

```{r}
set.seed(123) # for reproducibility

# Load Packages 
library(tidyverse) # for dplyr, ggplot, stringr, readr, purrr, tibble, tidyr etc 
library(readxl)
library(clusterProfiler) #GSEA includes gsea, enrichplot etc.
library(GOSemSim) # needed for simplify or now?
library(org.Rn.eg.db) # Rat genome anno pack- incl. AnnotationDbi
library(msigdbr) # MSigDB gene sets
library(enrichplot) # for dotplot()
library(ggridges) # for ridgeplot()
library(pathview) # pathview() - Kegg pathway visualisation

library(gganatogram) # gganatogram CO GG
library(drawCell) # drawing GO CC - SwissBioPics 
library(htmlwidgets) #
library(webshot2)

library(paletteer) # colors
library(colorspace) # colors
library(cowplot) # plot_grid

library(readxl)
library(writexl) # for excel tab export
library(ggvenn) # vennys (old ones)
library(scales) #label_wrap text break in lolliplots
```

### Load Data

```{r}
# #READ IN DATA
# KEGG
load("output/gsea_results/2026_01_12_KEGG_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t3.rda")

# GO
load("output/gsea_results/2026_01_12_GO_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t2.rda")

# GO simplified (was prev made in this script)
load("output/gsea_results/2026_01_24_GO_gsea_EExAge_cp_v3.4.2_t2_simplified.rda")

# MSIGDB
load("output/gsea_results/2026_01_12_gsea_msig_Hallmark_EExAge_mssv3.2.2_t1_cpv3.4.2_t2.rda")

# MSIGDB C2 Reactome 
load("output/gsea_results/2026_02_09_gsea_msig_c2_reactome_EExAge_mss3.2.2_t1_cp3.4.2.rda")
```

```{r}
up_subcell_raw <- read_excel(
  "input/db/UP_subcellular_locations_all_2026_01_23.xlsx")
```

```{r}
# mapped_comp_v3.2.2_EExAge_t1
load("input/protein_lists/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_comp.rda")

df <- mapped_comp_v3.2.2_EExAge_t1
```

------------------------------------------------------------------------

# Wrangling

### Protein Comparisons with ENTREZ & GENENAME

```{r}
# see BioIn_2025_12_v3.4.2_ClusterProfiler_EExAge_vis_testing_v1.Rmd for more info

protein_comp <- df %>%
  filter(is.na(issue)) %>% # keeps rows with issue == na (so comparisons that are ok)
  filter(!str_detect(log2FC, "Inf")) # remove infinity/missing fold change values

# check 
head(protein_comp) 
colnames(protein_comp)


# ENTREZ
protein_comp_uni_gene <- unique(protein_comp$gene) # 8014

bitr_gn_2_entrez <- bitr(protein_comp_uni_gene,
                         fromType = "SYMBOL",
                         toType = "ENTREZID",
                         OrgDb = "org.Rn.eg.db") #3.39% failed to map... better




# SEE MY LEVELS BELOW 
my_comp_levels = c("H_EE_vs_SH",
              "HxA_EE_YNG_vs_SH_YNG",
              "HxA_EE_OLD_vs_SH_OLD",
              "A_YNG_vs_OLD", 
              "HxA_EE_YNG_vs_EE_OLD",
              "HxA_SH_YNG_vs_SH_OLD",
              
              "HxA_EE_OLD_vs_SH_YNG", "HxA_EE_YNG_vs_SH_OLD"
)


# MAP ENTREZ TO UNIPROT PROT COMPS
protein_comp_entrez <- left_join(protein_comp, bitr_gn_2_entrez,
                                 by = join_by(gene == SYMBOL)) %>%
  filter(!is.na(ENTREZID))  # remove non mapped - 64384 to 61952 


protein_comp_entrez$Label <- factor(protein_comp_entrez$Label,
                                  levels = my_comp_levels)

```

### Map nested .rda to master dfs

```{r}
# # Map KEGG to a MASTER DF 
# KEGG_tibs_df <- map_dfr(KEGG_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t3$kegg_results_tib,
#                         as.data.frame,
#                         .id = "Label")  %>%
#   mutate(Description_2 = str_replace_all(Description, " and ", " & "), # & instead of and
#          .after = Description)
# 
# # MAP Msigdb Hallmarks to masterdf 
# HM_tibs_df <- map_dfr(gsea_msig_Hmrk_EExAge_mss3.2.2_t1_cp3.4.2_t2$gsea_results_tib,
#                         as.data.frame,
#                         .id = "Label")
# 
# 
# # MAP GO Simplified (nested nested) to single df
# GO_sim_tibs_df <- map_dfr(
#   GO_gsea_EExAge_cp_v3.4.2_t2_simplified$sim_GO_res_tib,
#   ~map_dfr(.x, as_tibble, .id = "GO"),
#   .id = "Label") 


# MAP MSIG c2 REACTOME 
REACT_tibs_df <- map_dfr(
  gsea_msig_c2_reactome_EExAge_mss3.2.2_t1_cp3.4.2$gsea_results_tib,
  as.data.frame,
  .id = "Label") %>%
  mutate(Description_2 = str_replace_all(Description, "REACTOME_", ""), 
         .after = Description)  %>%
  mutate(Description_3 = str_replace_all(Description_2, "_AND_", "_&_"), # needs 2 work
         .after = Description_2)  


```

```{r}
my_levels = c("H_EE_vs_SH",
              "HxA_EE_YNG_vs_SH_YNG",
              "HxA_EE_OLD_vs_SH_OLD",
              "A_YNG_vs_OLD", 
              "HxA_EE_YNG_vs_EE_OLD",
              "HxA_SH_YNG_vs_SH_OLD"
)


# KEGG 6 ORD
KEGG_tibs_df_6 <- KEGG_tibs_df %>%
  filter(!(Label %in% c("HxA_EE_OLD_vs_SH_YNG", "HxA_EE_YNG_vs_SH_OLD"))) 

KEGG_tibs_df_6$Label <- factor(KEGG_tibs_df_6$Label,
                                  levels = my_levels)

# GO 6 ORD
GO_sim_tibs_df_6 <- GO_sim_tibs_df  %>%
  filter(!(Label %in% c("HxA_EE_OLD_vs_SH_YNG", "HxA_EE_YNG_vs_SH_OLD"))) 

GO_sim_tibs_df_6$Label <- factor(GO_sim_tibs_df_6$Label,
          
                        levels = my_levels)


# REACTOME 
REACT_tibs_df_6 <- REACT_tibs_df %>%
   filter(!(Label %in% c("HxA_EE_OLD_vs_SH_YNG", "HxA_EE_YNG_vs_SH_OLD"))) 

REACT_tibs_df_6$Label <- factor(REACT_tibs_df_6$Label,
                                  levels = my_levels)


# # MSIGDB | "HxA_EE_OLD_vs_SH_OLD",
# 
# HM_tibs_df_6 <- HM_tibs_df  %>%
#   filter(!(Label %in% c("HxA_EE_OLD_vs_SH_YNG", "HxA_EE_YNG_vs_SH_OLD")))
# 
# HM_tibs_df_6$Label <- factor(HM_tibs_df$Label,
#                              levels = c("H_EE_vs_SH",
#                                         "HxA_EE_YNG_vs_SH_YNG",
#                                         # "HxA_EE_OLD_vs_SH_OLD",
#                                         "A_YNG_vs_OLD",
#                                         "HxA_EE_YNG_vs_EE_OLD",
#                                         "HxA_SH_YNG_vs_SH_OLD"))
# 
# # error idk
# #Error in `$<-.data.frame`(`*tmp*`, Label, value = c(1L, 1L, 1L, 1L, 1L,  :
# #  replacement has 25 rows, data has 19
```

```{r}
# note alot here don't have GOID anyway
colnames(up_subcell_raw)
str(up_subcell_raw)

up_subcell <- up_subcell_raw %>%

  tidyr::separate_wider_regex( # use this instead!
    `Gene Ontologies`,
    patterns = c(go_id = "GO:\\d+", # matches GO:0002079:
                 ":",
                 go_term = ".*"), # matches any char at end of string
    cols_remove = FALSE) %>%
  mutate(subcell_ID = str_remove(`Subcellular location ID`, "-"),
         .after = `Subcellular location ID`)

# note "SL-0181" rather than "SL0181" - sometimes varies?
```

```{r}
KEGG_counts <- KEGG_tibs_df %>%
  count(Label)
```

```{r}

```

------------------------------------------------------------------------

## Functions

### Lolliplot

```{r}
lolliplot <- function(data,
                      x_1 = Description, 
                      x_2 = NES, 
                      y = NES, 
                      fill = NES,
                      alpha = p.adjust,
                      facet_formula = ~Label,
                      size = setSize,
                      subtitle = NULL,
                      legend_pos = "none") {
  
  lol <- ggplot(data,
                aes(x = reorder({{x_1}},{{x_2}}),
                    y = {{y}},
                    fill = {{fill}}
                    )) +
    
    geom_segment(aes(x = {{x_1}},
                     yend = {{y}}, y = 0,
                     alpha = {{alpha}}
                     )) +
    
    geom_point(aes(alpha = {{alpha}},
                  size = {{size}}),
             shape = 21) +
    # scale_alpha(range = c(.95,.3)) + # rev alpha so darker = more sig | all
    scale_alpha(range = c(.95,.45)) + #  GO TRIM VERSION so matches others
    geom_hline(yintercept = 0, color = 'grey20', linewidth = 0.1) +
    scale_color_manual(breaks = c("Up", "Down"),
                     # values = c("#dc322f", "#268bd2"),
                     guide = 'none') + 
    # scale_size_continuous(range = c(3,9)) + # map size oflolly (set size)
    scale_size_continuous(range = c(2,8)) + # map size oflolly (set size) | GO BP
    
    # scale_fill_continuous_diverging("Blue-Red 3") + # colorspace
    scale_fill_continuous_diverging("Blue-Red 2") +
    
    scale_x_discrete(labels = scales::label_wrap(width = 50)) + # break text |
  
    ylim(-4,4)+
  
    labs(subtitle = subtitle,
       y = 'NES' ) +
    
    coord_flip() + #fliptheplot
    facet_wrap(facet_formula,
             space = 'free_x') +
    theme_bw() +
    theme(
    axis.text.x = element_text(angle = 90, hjust = 1, color = "grey15",
                               vjust = 0, # 90, hj1 t/R, vj.5 cent
                               size = 9.5, face = 'italic'), 
    axis.text.y = element_text(hjust = 1, color = "grey15",
                               size = 8.5, face = 'italic',
                               lineheight = .7), # <1 smaller distances breaks
    axis.title.y = element_blank(),
    strip.text = element_text(size = 8.5),
    
    # legend.margin = margin(-10,-1,-5,-1), # (top, right, bot, left) | bottom ver
    legend.title = element_text(face = 'italic', size =8,
                                hjust = 1),
    legend.key.size = grid::unit(0.4, "cm"), # posit answer to same height
    legend.text = element_text(margin = margin(l = 0)), # marg text & key
    legend.box.just = "right", # right justify legend box
    
    # FOR RIGHT LEGEND
    legend.margin = margin(0,0,0,-5), # (top, right, bot, left) | right ver
    legend.justification = "top", # for right ver
    
    legend.position = legend_pos) 
    
}
```

## Msigdb Hallmarks 8

```{r}
HM_lol <- lolliplot(HM_tibs_df, subtitle = "MSigDB Hallmarks", legend_pos = "bottom")
HM_lol

# exp 2026_01_31_EExAge_MSigDB_Hallmarks_v1 - 13.5 x 5
```

### KEGG lolliplots (6)

```{r}
# KEGG ALL 6
KEGG_lol_f6 <- lolliplot(KEGG_tibs_df_6,
                         x_1 = Description_2,
                         subtitle = "KEGG", legend_pos = "bottom")
KEGG_lol_f6 
# exp - 2026_01_31_EExAge_6_comps_KEGG_lolli_v1 12 x 12 

ggsave("testest.png", dpi = 200)
```

### GO lolliplots (6)

```{r}
GO_sim_lol_6 <-   GO_sim_tibs_df_6 %>%
  filter(GO == "BP") %>% # Swi
  lolliplot(subtitle = "GO BP GSEA - Housing & Age", legend_pos = "right")


GO_sim_lol_6
# 2026_02_25_GO_MF_sim_lol_6_v2 - MF v2 - 11.5 x 17
# 2026_02_25_GO_CC_sim_lol_6_v2 - 12 x 18
# 2026_02_25_GO_BP_sim_lol_6_v2 -14 x 21.5
```

## Msigdb C2 Reactome

```{r}
# REACTOME GSEA - 770 adjp<0.05(all 6) |  p.adjust <0.02 (550 obs) |p.01 405
REACT_lol_6 <- REACT_tibs_df_6 %>%
  filter(p.adjust <=0.01) %>%
  
  lolliplot(subtitle = "REACTOME (via Msigdbr C2)",
            x_1 = Description_2, legend_pos = "bottom")

REACT_lol_6


# ggsave("2026_02_25_REACTOME_via_Msigdbr_C2_EExAge_6.png", dpi = 200)
```

### Reactome EE

```{r}
REACT_lol_EE_3 <- REACT_tibs_df_6 %>%
  filter(Label %in% c("H_EE_vs_SH","HxA_EE_YNG_vs_SH_YNG","HxA_EE_OLD_vs_SH_OLD")) %>%
  filter(p.adjust <=0.011) %>%
  lolliplot(subtitle = "REACTOME GSEA (via msigdbr) - Housing",
            x_1 = Description_3,
            legend_pos = "right")

REACT_lol_EE_3

# 4 - 2026_02_25_REACTOME_via_Msigdbr_C2_EExAge4_trm_adjp01 - 14 x 23
# 3 - 2026_02_25_REACTOME_via_Msigdbr_C2_EE_3_trm_adjp011 - 13.5 x 20
```

#### EE KEGG lolli

```{r}
# KEGG 3 EE
KEGG_tibs_EE_3 <- KEGG_tibs_df_6 %>%
  filter(Label %in% c("H_EE_vs_SH","HxA_EE_YNG_vs_SH_YNG","HxA_EE_OLD_vs_SH_OLD")) %>%
  lolliplot(subtitle = "KEGG GSEA - Housing",
            x_1 = Description_2,
            legend_pos = "bottom")

KEGG_tibs_EE_3 
# exp - 2026_01_31_EE_3_comps_KEGG_lolli_v1 - 9 x 12
# exp - 2026_02_25_EE_3_comps_KEGG_lolli_v2.pdf = 9 x 12 - 40.7kb 
# ggsave("2026_02_23_EE_3_comps_KEGG_lolli_v2.png", dpi = 200) # 496kb 
```

#### 

------------------------------------------------------------------------

## Pathview for loops (14 02 2026)

Done a nooby lazy way maybe clean up later.

-   <https://www.bioconductor.org/packages/devel/bioc/vignettes/pathview/inst/doc/pathview.pdf>
-   rat kegg pathways - <https://www.kegg.jp/kegg-bin/show_organism?menu_type=pathway_maps&org=rno>
-   <https://igordot.github.io/msigdbr/articles/msigdbr-intro.html>

#### Aes test

```{r}
## Ribosome - rno03010 
pathview(gene.data=KEGG_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t3$geneList_vec$H_EE_vs_SH,
                pathway.id="rno03010",
                species = 'rno',
         out.suffix = "2026_02_14__H_EE_vs_SH_testing",
         kegg.native = T,
         same.layer = T, #slower & on top (out of bounds?)
         res = 600, #400 dpi (def 300 dpi for png) # not sure if changes anything..
         low = list(gene = "#3E76E8", cpd = "#A054A3"), # purple unused 
         mid = list(gene= "grey85", cpd = "grey85"), 
         high = list(gene = "#DA3558", cpd ="#F3AD6AFF"), # org unused
         new.signature = FALSE)

# my_colors <- c("#E22A47", "#DA3558", "#D33F6A", "#317DEC", "#3E76E8", "#4A6FE3" )
```

### Set up master gene vec lists

```{r}
# # get msigdbr kegg pathways into data 
# KEGG_rats_msig <- msigdbr(species = "Rattus norvegicus",
#                           collection = "C2", subcollection = "CP:KEGG_MEDICUS")
# nvm maybe return to later 
```

```{r}
length(unique(KEGG_tibs_df_6$ID)) # 67 

KEGG_multi <- KEGG_tibs_df_6 %>%
  group_by(Description) %>%
  count() %>%
  filter(n > 1)

KEGG_multi_list <- KEGG_multi$Description

# note - & - different?
KEGG_multi_df <- KEGG_tibs_df_6 %>% 
  filter(Description %in% KEGG_multi_list) %>%
  mutate(trm_des = str_replace_all(Description, "[- -()]", "")) %>%  # rm spaces, - & () 
  mutate(trm_desc = str_trunc(trm_des, 15, side = "right", ellipsis = "")) %>%
  filter(!(ID == "rno04723")) # rm reterograde endocannbinoid - not found pathbiew err 
```

```{r}
# Map KEGG to a MASTER genelist DF 
geneLists_df <- map_dfr(KEGG_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t3$geneList_vec,
                        ~enframe(.x),
                        .id = "Label")
```

```{r}
# iterate over... 
labels <- unique(KEGG_tibs_df_6$Label)

kegg_pathways <- unique(KEGG_multi_df$ID)
```

#### Extra Pathways

```{r}
# rm errors - metabolic pathways, fatty acid metabolism (rno01212) - too long
kegg_pathways_2_df <- data.frame("ID" = c("rno00010", # 1
                                          "rno04130", # 
                                          "rno04514", # 
                                          "rno04518", #
                                          "rno04722",
                                          "rno04024",
                                          "rno04151",
                                          "rno04010",
                                          "rno04014",
                                          "rno04020",
                                          "rno04022",
                                          "rno04081",
                                          "rno04150",
                                          "rno04080",
                                          "rno04512",
                                          "rno04060",
                                          "rno04517",
                                          "rno04210",
                                          "rno04110",
                                          "rno04810",
                                          "rno05022",
                                          "rno04211",
                                          "rno04724",
                                          "rno04726",
                                          "rno04720",
                                          "rno04730",
                                          "rno04725",
                                          "rno04728",
                                          "rno04120",
                                          "rno03008",
                                          "rno00970",
                                          "rno04141",
                                          "rno04144",
                                          "rno04145",
                                          "rno04146",
                                          "rno04142"
                                          ),
                                 
                                 "trm_desc" = c("glycolysis_gluc",
                                              "SNARE_int_vt",
                                              "CAM_interac",
                                              "Intergrin_sig",
                                              "Neurotrophic_sig",
                                              "cAMP_sig_path",
                                              "PI3K_Akt_sig_path",
                                              "MAPK_sig_path",
                                              "Ras_sig_path",
                                              "Calcium_sig_path",
                                              "cGMP_PKG_sig_path",
                                              "Hormone_sig",
                                              "mTOR_sig_path",
                                              "Neuract_lig_rep_i",
                                              "ECM_receptor_int",
                                              "Cytokine_rec_int",
                                              "IgSF_CAM_sig",
                                              "Apoptosis",
                                              "Cell_cycle",
                                              "Reg_actin_cytosk",
                                              "Paths_neurodegen",
                                              "longeivity_reg",
                                              "glutamaterg_synp",
                                              "serotonergic_syn",
                                              "LTP",
                                              "LTD",
                                              "cholinergic_syn",
                                              "dopaminergic_syn",
                                              "ubiquit_med_prtly",
                                              "ribosome_biogen",
                                              "Aminoacyl_tRNA_bi",
                                              "prot_proces_in_ER",
                                              "endocytosis",
                                              "phagosome",
                                              "peroxisome",
                                              "lysosome"
                                              ))

kegg_pathways_2 <- unique(kegg_pathways_2_df$ID)
```

#### for loop for KEGG pathviews

```{r}
# # PATHVIEW FOR LOOP 
# for (lb in labels) {
#   
#   wdf <- geneLists_df %>%
#     filter(Label == lb) %>%
#     dplyr::select(name, value)
#     
#   wgL <- tibble::deframe(wdf)
#   
#   #for (kp in kegg_pathways) {  # 1 kegg pathways from gsea
#   for (kp in kegg_pathways_2) { # 2 extra kegg paths of interest 
#     
#     # c_desc <- KEGG_multi_df %>%  # 1 kegg pathways from gsea
#      c_desc <- kegg_pathways_2_df %>%  # 2 extra kegg paths of interest 
#       filter(ID == kp) %>%
#       dplyr::select(trm_desc) %>%
#       slice_head(n = 1)
#     
#     
#     pathview(gene.data = wgL,
#                 pathway.id = kp,
#                 species = 'rno',
#          out.suffix = paste0(lb, "_", c_desc[1]),
#          kegg.native = T,
#          same.layer = T, #slower & on top (out of bounds?)
#          res = 600, #400 dpi (def 300 dpi for png) # nvm doesn't change drawings idk
#          low = list(gene = "#317DEC", cpd = "#A054A3"), # purple unused 
#          mid = list(gene= "grey85", cpd = "grey85"), 
#          high = list(gene = "#E22A47", cpd ="#F3AD6AFF"), # org unused
#          new.signature = FALSE
#          )
#   }
# }
# 
# #noob way manually set working directory as folder you want to output
```

------------------------------------------------------------------------

#### Running Scores

<https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#running-score-and-preranked-list-of-gsea-result>

```{r}
#head(KEGG_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t3$kegg_results$H_EE_vs_SH$Description, 20)

# 10 = Reterograde Endo cannm, 12 - synaptic vesicle, 20 neuroactive
# gseaplot2(KEGG_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t3$kegg_results$H_EE_vs_SH,
#           geneSetID = c(10,12, 20))


p1 <- gseaplot2(KEGG_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t3$kegg_results$H_EE_vs_SH,
                geneSetID = c(10,12, 20, 6:8, 1), subplots = 1:2,
                color = c("#D3F2A3FF", "#E17C05FF", "#586e75", "#F3AD6AFF",
                          "#F1B6DAFF", "#D43F23" ,"#CF597EFF"),
                title = "KEGG - EE vs SH (all)")

#head(KEGG_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t3$kegg_results$HxA_EE_YNG_vs_SH_YNG$Description, 50)
p2 <- gseaplot2(KEGG_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t3$kegg_results$HxA_EE_YNG_vs_SH_YNG,
          geneSetID = c(1, 9, 10, 22, 27, 31, 32, 46, 47), subplots = 1:2,
          color = c("#2896B5", "#589D4C", "#A054A3", "#E17C05FF",
                   "#F1B6DAFF", "#586e75", "#F3AD6AFF", "#D43F23" ,"#CF597EFF"),
          title = "KEGG - EE vs SH (young)")



p3 <- gseaplot2(KEGG_gsea_EExAge_mssv3.2.2t1_cpv3.4.2t3$kegg_results$HxA_EE_OLD_vs_SH_OLD,
          geneSetID = c(1,3), subplots = 1:2,
          color = c("#586e75", "#CF597EFF"), 
          title = "KEGG - EE vs SH (old)")


plot_list(p1, p2, p3, ncol = 1)
```

# go plots

```{r}
GO_sim_tibs_df_6 <- GO_sim_tibs_df %>%
  filter(!(Label %in% c("HxA_EE_OLD_vs_SH_YNG", "HxA_EE_YNG_vs_SH_OLD"))) 

GO_sim_tibs_df_6$Label <- factor(GO_sim_tibs_df_6$Label,
                                  levels = c("H_EE_vs_SH",
                                             "HxA_EE_YNG_vs_SH_YNG",
                                             "HxA_EE_OLD_vs_SH_OLD",
                                             "A_YNG_vs_OLD", 
                                             "HxA_EE_YNG_vs_EE_OLD",
                                             "HxA_SH_YNG_vs_SH_OLD"))


GO_sim_lol_6_CC <-   GO_sim_tibs_df_6 %>%
  filter(GO == "CC") %>%
  lolliplot()
GO_sim_lol_6_CC
```

```{r}
GO_sim_lol_3_EE <-   GO_sim_tibs_df_6 %>%
  filter(Label %in% c("H_EE_vs_SH","HxA_EE_YNG_vs_SH_YNG","HxA_EE_OLD_vs_SH_OLD")) %>%
  # filter(GO == "CC") %>% # Swi
  filter(p.adjust <= 0.031) %>% # cut of for BP so ~136
  filter(GO == "BP") %>% # Swi
  lolliplot(subtitle = "GO BP GSEA - Housing",
            legend_pos = "right")


GO_sim_lol_3_EE

# exp - 2026_01_31_EE_3_comps_GO_CC_sim_lolli_v1 - 9 x 12.75
# exp - 2026_01_31_EE_3_comps_GO_MF_sim_lolli_v1 - 9.25 x 10 | font 
# BP  2026_01_31_EE_3_comps_GO_BP_sim_lolli_adjp_03_trim_v1 - 9 x 13 |BP too long! 

#NEW VERSION
#CC - 2026_02_25_EE_3_comps_GO_CC_sim_lolli_v2 9.5 x 14
#MF 2026_02_25_EE_3_comps_GO_MF_sim_lolli_v2 - 9.5 x 13.5
#BP - 2026_02_25_EE_3_comps_GO_BP_sim_lolli_v2 - 10.25 x 16
#BP - 2026_02_25_EE_3_comps_GO_BP_sim_lolli_adjp03_v2 - 10 x 14.75
```

### exp - 2026_01_31_EE_3_comps_GO_CC_sim_lolli_v1

-   <https://emilhvitfeldt.github.io/paletteer/>

```{r}
# CONTINUOUS
# scico
paletteer::paletteer_c("scico::berlin", n = 10)
paletteer::paletteer_c("scico::roma", n = 10)
paletteer::paletteer_c("scico::hawaii", n = 10)


# DISCRETE 
# nord
paletteer::paletteer_d("nord::frost")
paletteer::paletteer_d("nord::aurora")
# Rcartocolor
paletteer::paletteer_d("rcartocolor::Sunset")
paletteer::paletteer_d("rcartocolor::PinkYl")
paletteer::paletteer_d("rcartocolor::OrYel")
paletteer::paletteer_d("rcartocolor::BluYl")
paletteer::paletteer_d("rcartocolor::Emrld")
paletteer::paletteer_d("rcartocolor::Teal")
paletteer::paletteer_d("rcartocolor::Safe")
paletteer::paletteer_d("rcartocolor::Prism")
paletteer::paletteer_d("rcartocolor::Temps")


# DYNAMIC
# cartography
paletteer::paletteer_dynamic("cartography::pink.pal", 6)
paletteer::paletteer_dynamic("cartography::wine.pal", 6)
paletteer::paletteer_dynamic("cartography::red.pal", 6)
paletteer::paletteer_dynamic("cartography::orange.pal", 6)
paletteer::paletteer_dynamic("cartography::sand.pal", 6)
paletteer::paletteer_dynamic("cartography::brown.pal", 6)
paletteer::paletteer_dynamic("cartography::kaki.pal", 6)
paletteer::paletteer_dynamic("cartography::green.pal", 6)
paletteer::paletteer_dynamic("cartography::turquoise.pal", 6)
paletteer::paletteer_dynamic("cartography::blue.pal", 6)
paletteer::paletteer_dynamic("cartography::purple.pal", 6)
paletteer::paletteer_dynamic("cartography::taupe.pal", 6)
paletteer::paletteer_dynamic("cartography::harmo.pal", 6)
```

```{r}
# JENN
GO_sim_EE_CC_map <- GO_sim_tibs_df_6 %>%
  filter(Label %in% c("H_EE_vs_SH","HxA_EE_YNG_vs_SH_YNG","HxA_EE_OLD_vs_SH_OLD"))  %>%
  filter(GO == "CC")  %>%
left_join(up_subcell, by = join_by(ID == go_id))
  

#colnames(GO_sim_EE_CC_map)
unique(GO_sim_EE_CC_map$`Is part of`)


# just for checking 
# write_xlsx(GO_sim_EE_CC_map, path = "output/2026_01_31_EE_cc_map_check_v1.xlsx")

GO_EE_CC <- GO_gsea_EExAge_msstats_v3.2.2_t1_cp_v3.4.2_t2$GO_results_tib$H_EE_vs_SH$CC 

GO_EE_CC_map <- left_join(GO_EE_CC, up_subcell, by = join_by(ID == go_id))
  
  
# write_xlsx(GO_EE_CC_map, path = "output/2026_02_01_EE_cc_longer_map_check_v2.xlsx")
```

```{r}
neuron_map_EE_cell_comp <- drawCell::drawCell(
  organism_identifier = "6072",
  list_sl_colors = list(
    "SL0191" = "#4a6fe3", # nucleus
    "SL0173" = "#CF597EFF", # mitochondrion
    "SL0132" = "#39B185FF", # golgi apparatus
    "SL0095" = "#5E81ACFF", # Ebdoplasmic reticulum
  #   "SL0101" = "#E17C05FF", # Endosome
    "SL0197" = "D33F6A", # Perikaryon / so`ma
  #   "SL0154" = "#A8DBD9FF", # Lipid Droplet
  #   "SL0158" = "#7CAF71FF", # Lysosome
    # "SL0091" = "#E6F5D0FF", # Cytosol
  #   "SL0090" = "#E6AB02FF", # Cytoskeleton
    # "SL0098" = "#d1eeea", # endoplasmic ret- golgi intermediate
    "SL0279" = "#e07b91", # axon
  #   "SL0288" = "#97E196FF", # growth cone
    "SL0176" = "#e6afb9", # Myelin membrane
    "SL0192" = "#d33f6a", # Paranodal septate junction
    "SL0071" = "#d46780", # clathrin-coated vesicle (membrane)
  #   "SL0284" = "#F9C7B8FF", # dendrite
  #   "SL0258" = "#F3AD6AFF", # synapse
  #   "SL0297" = "#586F9AFF", # post synaptic density?
  #   "SL0219" = "#DB7B80FF", # postsynaptic cell mem 
  #   "SL0284" = "#EE4D5AFF", # Dendritc Spine
  #   "SL0285" = "#F46D43FF", # Dendritc Spine mem
  #   "SL0530" = "#68ABB8FF", # Spine Apparatu mem
  #   
    "SL0222" = "#F1B6DAFF", # presynaptic cell mem
  #   "SL0519" = "#EDAD08FF", # presyn active zone
    "SL0529" = "#d33f6a", # presynap endocytic zone
    # "SL0259" = "#4C90B4FF", # Synaptic Vesicle
    "SL0260" = "#d33f6a", # Synap Vesic Mem
    "SL0039" = "#EB7F86FF" # Cell membrane
  
  ),
  # width = 2000,
  width = 1500,
  height = 500
)

neuron_map_EE_cell_comp

# saveWidget(neuron_map_2026_01_28, "neuron_map_2026_01_28.html")
# 
# webshot(url = "neuron_map_2026_01_28.html",
#         file = "neuron_map_2026_01_28.pdf",
#         # file = "temp.png",
#         #vwidth = 600,
#         #vheight = 300,
#         delay = 10 # adding delay fixes problem (slow! otherwise blanks)
#         )
```

------------------------------------------------------------------------

-   <https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#enrichment-map>

-   <https://dshizuka.github.io/networkanalysis/03_plots.html>

```{r}
# WEIRD MAPPING ?!?!?! 
p1 <- treeplot(
  GO_gsea_EExAge_cp_v3.4.2_t2_simplified$pw_sim_GO_terms$H_EE_vs_SH$CC, nCluster = 5) +
  theme(legend.position = "none")

p2 <- treeplot(
  GO_gsea_EExAge_cp_v3.4.2_t2_simplified$pw_sim_GO_terms$HxA_EE_YNG_vs_SH_YNG$CC,
  nCluster = 5) +
  theme(legend.position = "none")

aplot::plot_list(p1, p2, tag_levels='A', ncol=2)
```

```{r}
set.seed(123)

p1_test <- emapplot(
  GO_gsea_EExAge_cp_v3.4.2_t2_simplified$pw_sim_GO_terms$H_EE_vs_SH$CC, color = "NES",
  showCategory = 30, min_edge = 0.2, 
  nWords = 10, # tricks it into not adding extra label! def is 4 btw
  layout="nicely",
  node_label = "cateogry", group = TRUE
  ) +
  scale_color_continuous_diverging("Blue-Red 2") +
  scale_fill_discrete_divergingx("Temps") +
  theme(legend.position = "none")  +
 geom_cnet_label(node_label = "all", size = 3.5, color = "grey10", fontface = "italic")

p1_test


```

```{r}
set.seed(123)

p1 <- emapplot(
  GO_gsea_EExAge_cp_v3.4.2_t2_simplified$pw_sim_GO_terms$H_EE_vs_SH$CC, color = "NES",
  showCategory = 50, min_edge = 0.3, size_edge = 0.35, size_category = 1.7,
  layout="with_fr", node_label = "none", label_format = 3) +
  scale_color_continuous_diverging("Blue-Red 2") +
  scale_fill_discrete_divergingx("Temps") +
  theme(legend.position = "none")  +
 geom_cnet_label(node_label = "all", size = 4, fontface = "italic")


p1

p2 <- emapplot(
  GO_gsea_EExAge_cp_v3.4.2_t2_simplified$pw_sim_GO_terms$H_EE_vs_SH$BP, color = "NES",
  showCategory = 50, min_edge = 0.3, size_edge = 0.35, size_category = 1.7,
  layout="with_fr", node_label = "none", label_format = 3) +
  scale_color_continuous_diverging("Blue-Red 2") +
  scale_fill_discrete_divergingx("Temps") +
  theme(legend.position = "none")  +
 geom_cnet_label(node_label = "all", size = 4, fontface = "italic")

p2

p3 <- emapplot(
  GO_gsea_EExAge_cp_v3.4.2_t2_simplified$pw_sim_GO_terms$H_EE_vs_SH$MF, color = "NES",
  showCategory = 50, min_edge = 0.3, size_edge = 0.35, size_category = 1.7,
  layout="nicely", node_label = "none") +
  scale_color_continuous_diverging("Blue-Red 2") +
  scale_fill_discrete_divergingx("Temps") +
  theme(legend.position = "none")  +
 geom_cnet_label(node_label = "all", size = 3.5, fontface = "italic")

p3
```

```{r}
set.seed(123)

# p4 <- emapplot(
#   GO_gsea_EExAge_cp_v3.4.2_t2_simplified$pw_sim_GO_terms$A_YNG_vs_OLD$CC, color = "NES",
#   showCategory = 50, min_edge = 0.3, size_edge = 0.35, size_category = 1.5,
#   layout="with_fr", node_label = "none", label_format = 3) +
#   scale_color_continuous_diverging("Blue-Red 2") +
#   scale_fill_discrete_divergingx("Temps") +
#   theme(legend.position = "none")  +
#  geom_cnet_label(node_label = "all", size = 4, fontface = "italic")
# 
# p4


p5 <- emapplot(
  GO_gsea_EExAge_cp_v3.4.2_t2_simplified$pw_sim_GO_terms$A_YNG_vs_OLD$BP, color = "NES",
  showCategory = 50, min_edge = 0.3, size_edge = 0.35, size_category = 1.5,
  layout="with_fr", node_label = "none", label_format = 3) +
  scale_color_continuous_diverging("Blue-Red 2") +
  scale_fill_discrete_divergingx("Temps") +
  theme(legend.position = "none")  +
 geom_cnet_label(node_label = "all", size = 3.5, fontface = "italic")

p5


p6 <- emapplot(
  GO_gsea_EExAge_cp_v3.4.2_t2_simplified$pw_sim_GO_terms$A_YNG_vs_OLD$MF, color = "NES",
  showCategory = 50, min_edge = 0.3, size_edge = 0.35, size_category = 1.5,
  layout="nicely", node_label = "none") +
  scale_color_continuous_diverging("Blue-Red 2") +
  scale_fill_discrete_divergingx("Temps") +
  theme(legend.position = "none")  +
 geom_cnet_label(node_label = "all", size = 3.5, fontface = "italic")

p6
```

------------------------------------------------------------------------

## Vennys for GO

map() function from purrr <https://purrr.tidyverse.org/reference/map.html>

```{r}
# - Make individual GO  lists
# break up the df into separatre lists
GO_CC_up_lists <- GO_sim_tibs_df %>%
  filter(GO == "CC" & NES > 0) %>% # filter for CC
  split(.$Label) %>% # filter split by comparison label
  map(~pull(., Description)) 


GO_CC_down_lists <- GO_sim_tibs_df %>%
  filter(GO == "CC" & NES < 0) %>% # filter for CC
  split(.$Label) %>% # filter split by comparison label
  map(~pull(., Description)) 
```

```{r}
venny <- function(data, colors = NULL) {
  v <- ggvenn(data,
              digits = 0,
              # show_elements = TRUE,
              fill_alpha = 0.45,
              stroke_size = 0.5,
              set_name_size = 3.5,
              text_size = 3.2,
              fill_color = colors
              )
}
```

```{r}

EE_colors <- c('#5A844D', '#4782bf', '#C15574')

EE_CC_up <- GO_CC_up_lists[c(
  'H_EE_vs_SH', 'HxA_EE_YNG_vs_SH_YNG', 'HxA_EE_OLD_vs_SH_OLD')]

v1 <- venny(data = EE_CC_up, colors = EE_colors)

v1 


EE_CC_down <- GO_CC_down_lists[c(
  'H_EE_vs_SH', 'HxA_EE_YNG_vs_SH_YNG', 'HxA_EE_OLD_vs_SH_OLD')]

v2 <- venny(data = EE_CC_down, colors = EE_colors)

v2

```

```{r}

EExA_CC <- GO_CC_lists[c('H_EE_vs_SH', 'A_YNG_vs_OLD')]
v2 <- venny(data = EExA_CC, colors = c('#4782bf', '#CEAA33'))

v2
```

------------------------------------------------------------------------

------------------------------------------------------------------------

## Plot back GSEA volcanos

-   <https://www.kegg.jp/kegg-bin/show_organism?menu_type=pathway_maps&org=rno>
-   <https://en.wikipedia.org/wiki/Shades_of_orange>

KEGG_tibs_df_6_split

```{r}
str(KEGG_tibs_df_6) # lil check
#unique(KEGG_tibs_df_6$core_enrichment) 
  

KEGG_tibs_df_6_entrez_split <- KEGG_tibs_df_6 %>%  # 104 x 12s
  mutate(core_enrich_split = str_split(core_enrichment, "/")) %>% # split by /
  tidyr::unnest(core_enrich_split) %>% # unnest | to  3816 x 13
  left_join(bitr_gn_2_entrez, by = join_by(core_enrich_split == ENTREZID))  # map 2 gene name

```

```{r}
# iterate over... 
#labels <- unique(KEGG_tibs_df_6$Label)

# GET KEGG PATHVWAYS OF INTEREST 
kegg_POI  <- c(
  # "rno04722", "rno04724", # neurotrophin signalling,  GLUTsyn,
  "rno04721", "rno04082", "rno04723", # syanp_ves, neuroa_lig, ret_endoca
  "rno04360",  "rno04727", # axon_guid, GLUTsyn, GABAsyn
  "rno00900", # terpenoid backbone synthesis
  "rno00190", "rno00020",  # oxidati phos, TCA, 
  "rno03040", "rno03082", "rno03050", # spliceo, ATPchromatre, proteasom
  "rno03010") # ribosome


# EMPTY PLOT LIST 
kegg_volcano_list <-  vector(mode = "list")
```

```{r}
for(kp in kegg_POI) {

  my_kpg <- KEGG_tibs_df_6_entrez_split %>%
    filter(ID == kp) %>%
    dplyr::distinct(SYMBOL) %>%
    tibble::deframe()
  
  my_title <- KEGG_tibs_df_6_entrez_split %>%
    filter(ID == kp) %>%
    dplyr::distinct(Description) %>%
    tibble::deframe()
    
  my_kp_prot <- protein_comp_entrez %>%
    filter(Label %in% c("H_EE_vs_SH","HxA_EE_YNG_vs_SH_YNG","HxA_EE_OLD_vs_SH_OLD",
                        "A_YNG_vs_OLD")) %>%
    # filter(!(Label %in% c("HxA_EE_OLD_vs_SH_YNG", "HxA_EE_YNG_vs_SH_OLD"))) %>%
    filter(gene %in% my_kpg)
  
  
  vol_plot <- protein_comp_entrez %>%
        filter(Label %in% c("H_EE_vs_SH","HxA_EE_YNG_vs_SH_YNG","HxA_EE_OLD_vs_SH_OLD",
                        "A_YNG_vs_OLD")) %>%
       # filter(!(Label %in% c("HxA_EE_OLD_vs_SH_YNG", "HxA_EE_YNG_vs_SH_OLD"))) %>%
    
   ggplot(aes(x = log2FC, y = -log10(adj.pvalue))) +
    
    geom_point(aes(color = case_when( # conditional ass for color mapping
    adj.pvalue < 0.05 & log2FC > 0 ~ "up_adjp.05", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "down_adjp.05", # down sig .05
    adj.pvalue < 0.1 & log2FC > 0 ~ "up_adjp.1", # up 0.1
    adj.pvalue < 0.1 & log2FC < 0 ~ "down_adjp.1", # down .1
    TRUE ~ "ns" )), # catch the rest
    alpha = .35, size = 1.6, shape = 1) +

  scale_color_manual(values = c("firebrick", # coloring
                                "royalblue3",
                                "lightpink",
                                "lightblue3",
                                "grey100"),
                     breaks = c("up_adjp.05",
                                "down_adjp.05",
                                "up_adjp.1",
                                "down_adjp.1"),
                     labels = c("\U2191 (adj.p <.05)",
                                "\U2193 (adj.p <.05)",
                                "\U2191 (adj.p <.1)",
                                "\U2193 (adj.p <.1)")) +
    
     geom_point(data = my_kp_prot,
                aes(x = log2FC, y = -log10(adj.pvalue)),
                alpha = .35, size = 1.5, shape = 21,
                fill = "#E17C05FF", color = "#FCA842FF") + 

    
     # geom_text_repel(data = my_kp_prot,
     #            aes(label = gene),
     #            alpha = .3, size = 1, shape = 19, color = "orange") +
    
    # xlim(-1.5,1.5) +
    # ylim(0,5) +
    
    
    scale_x_continuous(limits = c(-2,2),
                       expand = c(0, 0)) +
    scale_y_continuous(limits = c(0,6),
                       expand = c(.04, 0)) + 
    
    geom_hline(yintercept = -log10(0.05),
             linetype = "dotted", linewidth = 0.1,
             color = "grey30") +
    geom_hline(yintercept = -log10(0.1),linetype = "dotted",
             linewidth = 0.1, color = "grey50") +
    geom_vline(xintercept = c(0),linetype = "solid",
             linewidth = 0.1, color = "#74025FFF") +

    
    labs(subtitle = my_title) +
     

    facet_wrap(~Label, nrow = 1) + 
     
    theme_bw() +
    theme(legend.position = "none",
          plot.subtitle = element_text(size =10),
          axis.title = element_text(size =8),
           axis.text = element_text(size =7.5),
          strip.text = element_text(size = 7.5),
          panel.grid = element_blank()
        )
    
    
    print(vol_plot)
    
    
    kegg_volcano_list[[kp]] <- vol_plot
  
}

```

```{r}
plot_grid(plotlist = kegg_volcano_list[c(1:3,5)], ncol = 2)

ggsave("2026_02_25_KEGG_EE_syn_volcanos_200dpi.png", dpi = 200)
```

REACTOME

```{r}
REACT_tibs_df_6_entrez_split <- REACT_tibs_df_6 %>%
  mutate(core_enrich_split = str_split(core_enrichment, "/")) %>% # split by /
  tidyr::unnest(core_enrich_split) %>% # unnest | to  3816 x 13
  left_join(bitr_gn_2_entrez, by = join_by(core_enrich_split == ENTREZID)) %>% #map2gene
  mutate()
```

```{r}
check_REACT_paths <- REACT_tibs_df_6 %>%
  filter(Label %in% c("H_EE_vs_SH","HxA_EE_YNG_vs_SH_YNG","HxA_EE_OLD_vs_SH_OLD")) %>%
  filter(p.adjust < 0.011) %>%
  arrange(p.ajust) %>%
  distinct(ID)

check_REACT_paths
```

```{r}
# GET REACTOME PATHVWAYS OF INTEREST 
REACT_POI  <- c(
  "REACTOME_PROLONGED_ERK_ACTIVATION_EVENTS",
  "REACTOME_DISEASES_OF_SIGNAL_TRANSDUCTION_BY_GROWTH_FACTOR_RECEPTORS_AND_SECOND_MESSENGERS",
  "REACTOME_INTRACELLULAR_SIGNALING_BY_SECOND_MESSENGERS",
  "REACTOME_REGULATION_OF_RAS_BY_GAPS",
    # "REACTOME_PTEN_REGULATION",
   'REACTOME_NEUROTRANSMITTER_RELEASE_CYCLE',
   "REACTOME_GABA_SYNTHESIS_RELEASE_REUPTAKE_AND_DEGRADATION",
   "REACTOME_TRANSMISSION_ACROSS_CHEMICAL_SYNAPSES",
   "REACTOME_LGI_ADAM_INTERACTIONS",
   "REACTOME_GLUTAMATE_NEUROTRANSMITTER_RELEASE_CYCLE",
   "REACTOME_INTERACTION_BETWEEN_L1_AND_ANKYRINS",
   "REACTOME_TRAFFICKING_OF_AMPA_RECEPTORS",
   "REACTOME_NEURONAL_SYSTEM",
   "REACTOME_L1CAM_INTERACTIONS",
   "REACTOME_NERVOUS_SYSTEM_DEVELOPMENT",
   "REACTOME_ECM_PROTEOGLYCANS",
   
   # "REACTOME_AXON_GUIDANCE", #not in herte
   "REACTOME_AGGREPHAGY",
   "REACTOME_SELECTIVE_AUTOPHAGY",
  
   "REACTOME_CHOLESTEROL_BIOSYNTHESIS"
  
  )

# EMPTY PLOT LIST 
reactome_volcano_list <-  vector(mode = "list")
```

```{r}
for(rct in REACT_POI) {

  my_rct <- REACT_tibs_df_6_entrez_split %>%
    filter(ID == rct) %>%
    dplyr::distinct(SYMBOL) %>%
    tibble::deframe()
  
  my_title <- REACT_tibs_df_6_entrez_split %>%
    filter(ID == rct) %>%
    dplyr::distinct(Description) %>%
    tibble::deframe()
    
  my_rct_prot <- protein_comp_entrez %>%
    filter(Label %in% c("H_EE_vs_SH","HxA_EE_YNG_vs_SH_YNG","HxA_EE_OLD_vs_SH_OLD",
                        "A_YNG_vs_OLD")) %>%
    # filter(!(Label %in% c("HxA_EE_OLD_vs_SH_YNG", "HxA_EE_YNG_vs_SH_OLD"))) %>%
    filter(gene %in% my_rct) %>%
    dplyr::group_by(Label) %>%
    mutate(rct_up = sum(log2FC > 0), # up
          rct_down = sum(log2FC < 0)) 

    
  my_rct_prot_sums <- my_rct_prot %>%
    dplyr::select(Label, rct_up, rct_down) %>%
    unique() # use for anno (this is to avoid overplottting)

  
  
  vol_plot <- protein_comp_entrez %>%
        filter(Label %in% c("H_EE_vs_SH","HxA_EE_YNG_vs_SH_YNG","HxA_EE_OLD_vs_SH_OLD",
                        "A_YNG_vs_OLD")) %>%
       # filter(!(Label %in% c("HxA_EE_OLD_vs_SH_YNG", "HxA_EE_YNG_vs_SH_OLD"))) %>%
    
   ggplot(aes(x = log2FC, y = -log10(adj.pvalue))) +
    
    geom_point(aes(color = case_when( # conditional ass for color mapping
    adj.pvalue < 0.05 & log2FC > 0 ~ "up_adjp.05", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "down_adjp.05", # down sig .05
    adj.pvalue < 0.1 & log2FC > 0 ~ "up_adjp.1", # up 0.1
    adj.pvalue < 0.1 & log2FC < 0 ~ "down_adjp.1", # down .1
    TRUE ~ "ns" )), # catch the rest
    alpha = .35, size = 1.6, shape = 1) +

  scale_color_manual(values = c("firebrick", # coloring
                                "royalblue3",
                                "lightpink",
                                "lightblue3",
                                "grey100"),
                     breaks = c("up_adjp.05",
                                "down_adjp.05",
                                "up_adjp.1",
                                "down_adjp.1"),
                     labels = c("\U2191 (adj.p <.05)",
                                "\U2193 (adj.p <.05)",
                                "\U2191 (adj.p <.1)",
                                "\U2193 (adj.p <.1)")) +
    
     geom_point(data = my_rct_prot,
                aes(x = log2FC, y = -log10(adj.pvalue)),
                alpha = .35, size = 1.5, shape = 21,
                fill = "#E17C05FF", color = "#FCA842FF") + 

  # geom_text_repel(max.overlaps = 27, size = 3, # gene text on points
  #                 color = "grey10") +
  
  # NUM SIG UP & DOWN! | use sep df, overwise overplots
  geom_text(data = my_rct_prot_sums, # up 
            aes(label = paste0(rct_up, " \U2191")),
            x = 1.5, y = 5.7, size = 2.7, color = "firebrick") + 
  geom_text(data = my_rct_prot_sums, # down
            aes(label = paste0(rct_down, " \U2193")),
            x = -1.5, y = 5.7, size = 2.7, color = "royalblue3") + 


    scale_x_continuous(limits = c(-2,2), expand = c(0, 0)) +
    scale_y_continuous(limits = c(0,6), expand = c(.04, 0)) + 
    
    geom_hline(yintercept = -log10(0.05),
             linetype = "dotted", linewidth = 0.1,
             color = "grey30") +
    geom_hline(yintercept = -log10(0.1),linetype = "dotted",
             linewidth = 0.1, color = "grey50") +
    geom_vline(xintercept = c(0),linetype = "solid",
             linewidth = 0.1, color = "#74025FFF") +
    
    labs(subtitle = my_title) +
     
    facet_wrap(~Label, nrow = 1) + 
     
    theme_bw() +
    theme(legend.position = "none",
          plot.subtitle = element_text(size =8.5, vjust = 0),
          axis.title = element_text(size =7.5),
           axis.text = element_text(size =7),
          axis.ticks = element_blank(),
          strip.text = element_text(size = 7.5),
          panel.grid = element_blank()
        )
    
    print(vol_plot)
    
    reactome_volcano_list[[rct]] <- vol_plot
  
}

```

```{r}
plot_grid(plotlist = reactome_volcano_list[1:18], ncol = 3)

# ggsave("2026_02_25_REACT_volcanos_200dpi_18_test.png", dpi = 200)
```
