---
title: "2026_06_v3.2.2_curated_gene&protein_sets_v1.Rmd"
author: "Stephanie Huang"
date: "2026-06-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library
```{r}

```

```{r}
load("input/db/rat_ref_proteome_2025_12_13_51872x295.rda")

rat_ref <- rat_ref_proteome_2025_12_13
```


```{r}
# colnames(rat_ref)

rat_ref_myelin <- rat_ref %>%
  filter(if_any(c(`Subcellular.location..CC.`, `Function..CC.`, Protein.names, Protein.families),
                ~ str_detect(., regex("myelin|paranode|ranvier", ignore_case = TRUE)))) %>%
  dplyr::select(Entry,`Gene.Names..primary.`, `Protein.names`, `Protein.families`, `Subcellular.location..CC.`,
         `Gene.Ontology..cellular.component.`, `Developmental.stage`,
          "Keywords"   ) 
```


```{r}
rat_ref_neurotrophin <- rat_ref %>%
    filter(if_any(c(`Subcellular.location..CC.`, `Function..CC.`, Protein.names, Protein.families),
                ~ str_detect(., regex("bdnf|neurotrophin|neuritin|p75|Trk|matrix metalloproteinase", ignore_case = TRUE)))) %>%
  dplyr::select(Entry,`Gene.Names..primary.`, `Protein.names`, `Protein.families`, `Subcellular.location..CC.`,
         `Gene.Ontology..cellular.component.`, `Developmental.stage`,
          "Keywords"   ) 


unique_neurotrophin <- unique(rat_ref_neurotrophin$Gene.Names..primary.)
```

```{r}
# BDNF STRING-DB Interactors
# https://string-db.org/cgi/network?taskId=bv7cE0w9aR2Y&sessionId=bwBMkcc7kFNo
BDNF_STRING <- c("Bdnf", "Ngfr", "Ntrk1",  "Ntrk2",  "Ntrk3",  "Sort1", "Ntf4",
                 "Gdnf", "Ntf3", "Cntf", "Creb1")
```


```{r}
rat_ref_growth_factor <- rat_ref %>%
    filter(if_any(c(Protein.names, Protein.families),
                ~ str_detect(., regex("growth factor", ignore_case = TRUE)))) %>%
  dplyr::select(Entry,`Gene.Names..primary.`, `Protein.names`, `Protein.families`, `Subcellular.location..CC.`,
         `Gene.Ontology..cellular.component.`, `Developmental.stage`,
          "Keywords"   ) 


unique_growth_factors <- unique(rat_ref_growth_factor$Gene.Names..primary.)
```

```{r}
rat_ref_neurogenesis <- rat_ref %>%
  filter(str_detect(Keywords, regex("neurogenesis", ignore_case = TRUE))) %>%
    dplyr::select(Entry,`Gene.Names..primary.`, `Protein.names`, `Protein.families`, `Subcellular.location..CC.`,
         `Gene.Ontology..cellular.component.`, `Developmental.stage`,
          "Keywords"   ) 
```

