---
title: "2026_02_mss_3.1.2_sp_pairwise_vis"
author: "Stephanie Huang"
date: "2026-02-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Quick graphs for pairwise counts & pairwise volcano plots!

2026_02_18 & 2026_07_24 - for PhD write up

***General notes***

1.  Sex/Batch - there are lots of "oneConditionMissing" in the NA column, these are largely from running across years & the gradient issue.
2.  

## Setup & Load

```{r}
library(tidyverse)
library(readr)
library(ggrepel) #  for geom_text_repel()
library(colorspace)
library(cowplot)
library(gt)
```

```{r}
# fasta used to search (includes sp)
up_fasta <- read_csv("input/db/UP000002494_10116_Rat_Ref_Proteome_22403_1pspg_2025_04_UPfastadf.csv")
```

```{r}
# full uniprot 295 cols data
load("input/db/rat_ref_proteome_2025_12_13_51872x295.rda")
```

```{r}
rat_ref_trm <- rat_ref_proteome_2025_12_13 %>%
  select(Entry,
         Protein.families, Pathway, Keywords, Developmental.stage,
         Induction, Function..CC., Subcellular.location..CC.)
```

```{r}
pw_litter <- read_csv("output/MSstatsTMT/comp/2025_12_31_sp_test_pairwise_msstats_v3.1.2_t6_litter.csv")
pw_sex <- read_csv("output/MSstatsTMT/comp/2025_12_31_sp_test_pairwise_msstats_v3.1.2_t5_sex.csv")
pw_beh <- read_csv("output/MSstatsTMT/comp/2025_12_31_sp_test_pairwise_msstats_v3.1.2_t4_behaviour.csv")
pw_cohort <- read_csv("output/MSstatsTMT/comp/2025_12_31_sp_test_pairwise_msstats_v3.1.2_t3_cohort.csv")
pw_housing <- read_csv("output/MSstatsTMT/comp/2025_12_31_sp_test_pairwise_msstats_v3.1.2_t1_housing.csv")
```

## Merge Data

```{r}
# combined df of all conditions
com_df <- bind_rows(list(Housing = pw_housing,
                         Sex = pw_sex,
                         Cohort = pw_cohort,
                         ExpH = pw_beh,
                         Litter = pw_litter),
                    .id = "pairwise.comp") %>%
  left_join(up_fasta,
            by = join_by(Protein == uniprot_acc))
  
```

```{r}
# # WRITE OUT MERGED & MAPPED! (note - raw & unfiltered!)
# write_excel_csv(com_df,
#                 "output/2025_12_31_sp_test_pairwise_msstats_v3.1.2_all_merge_map.csv")
# save(com_df,
#      file = "output/2025_12_31_sp_test_pairwise_msstats_v3.1.2_all_merge_map.rda")
```

```{r}
# Load in here if needed. 
```

### A bit messy...

```{r}
com_df_mapped <- com_df %>%
  
  # Filtering 
  filter(is.na(issue)) %>% # no issues  
  filter(is.numeric(adj.pvalue)) %>%  
  filter(!is.na(adj.pvalue)) %>% # fixes NA issue? 
  select(!c(...1, issue)) %>% # rm extra cols
  
  #___FOR_VOLCANO_ANNOTATION_______________
  # Make Gene Label for Sig
  mutate(sig_g_label = if_else(adj.pvalue <= .1, # can text label if up to adj.pvlue 
                               gene, NA)) %>%
  # Make one for no of sig up & down for each comaprison group/label
  group_by(Label) %>%
  mutate(Direction = if_else(log2FC > 0, "Up", "Down")) %>%
  mutate(sig_no_up_lab = sum(adj.pvalue < 0.05 & log2FC > 0), # up
         sig_no_down_lab = sum(adj.pvalue < 0.05 & log2FC < 0)) %>%  #  down
  
  #___FOR_TALLY_TABLE_&_NUMBER_REPORTED______________
  # Make Tally/combined 
  mutate(sig_no = sig_no_up_lab + sig_no_down_lab, # total sig per label
         smodel_no = n(), # no.sucessful modelled proteins by label -since issue rm abv
         model_no = 4562) %>% # no_modelled (no removals)
  ungroup()

colnames(com_df_mapped)
```

```{r}
# # massive merged df! 
# com_df_mapped_fam <- com_df_mapped %>%
#   left_join(rat_ref_trm, by = join_by(Protein == Entry))
```

```{r}
# com_df_mapped_sig <- com_df_mapped_fam  %>%
#   select(!c(...1, issue)) %>%
#   filter(adj.pvalue  <= 0.05) 
```

```{r}
# sig counts table 
sig_counts <- com_df_mapped %>%
  select(pairwise.comp, Label, sig_no_up_lab:model_no) %>%
  group_by(pairwise.comp, Label) %>% # not needed?
  unique() %>%
  mutate(smodel_per = round(smodel_no/model_no*100,2), # per of successful modelled
         sig_per = round(sig_no/model_no*100,2), #
         sig_per_up = round(sig_no_up_lab/model_no*100,2), #
         sig_per_down = round(sig_no_down_lab/model_no*100,2)) #

# sig_counts
colnames(sig_counts)

sig_counts$pairwise.comp <- factor(sig_counts$pairwise.comp,
                                   levels = c("Housing", "ExpH", "Cohort", "Litter", "Sex"))
```

4562

```{r}
sig_counts_gt <- sig_counts %>%
  select(pairwise.comp, Label,
         sig_no, sig_per,
         sig_no_up_lab, sig_per_up,
         sig_no_down_lab, sig_per_down,
         smodel_no, smodel_per) %>% # org cols
  

  gt(
    groupname_col = "pairwise.comp",
    rowname_col = "Label"
  ) %>%
  
    opt_vertical_padding(scale = 0.3) %>% # vert padding

   tab_options(# GENERAL TABLE OPTIONS
    table.font.size = 12
  ) 


sig_counts_gt
```

### Count of Significant proteins by pairwise comparison

```{r}
# hcl_palettes(plot = TRUE)

count_plot <- sig_counts_fil %>%
  # filter(sig == 1) %>%
  ggplot(aes(x = reorder(Label, n), y = n, fill = pairwise_comp)) +
   geom_col(stat = "identity", # so col sam wid
    width = .7, alpha = 0.7, color = "grey15") +
  scale_fill_discrete_qualitative(palette = "Set 2") +
  facet_wrap(~pairwise_comp, nrow = 1, scales = 'free_x', space = 'free_x') +
  theme_bw() +
  labs(y = "no. of significant proteins by pairwise comparison \n (adj.pvalue <.05) (sp db)") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust =1, vjust = 0.5, face = "italic"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(color ="grey15", size = 10),
        strip.text = element_text(size = 7.5))

count_plot
```

```{r}
top_5 <- com_df_mapped_fam %>% 
  group_by(pairwise_comp, Label) %>%
  slice_min(adj.pvalue, n = 10, with_ties = FALSE)
```

## 

------------------------------------------------------------------------

No Litter volcano plots

```{r}
# make new df for the geom_text bit below.
# prev had from 1 df but over plots repeately & cant index since mapped_comp huge.
sig_volcano_sum_no_litter <- com_df_mapped %>%
  filter(pairwise_comp != "litter") %>%
  dplyr::select(Label, sig_no_up_lab, sig_no_down_lab) %>%
  unique() 
  

```

```{r}
big_volcano_no_lit <- com_df_mapped %>%
  
   filter(pairwise_comp != "litter") %>%
  
  ggplot(aes(x = log2FC, y = -log10(adj.pvalue), label = sig_g_label)) +
  
  # POINTS
  geom_point(aes(color = case_when( # conditional ass for color mapping
    adj.pvalue < 0.05 & log2FC > 0 ~ "up_adjp.05", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "down_adjp.05", # down sig .05
    adj.pvalue < 0.1 & log2FC > 0 ~ "up_adjp.1", # up 0.1
    adj.pvalue < 0.1 & log2FC < 0 ~ "down_adjp.1", # down .1
    TRUE ~ "ns" )), # catch the rest
    alpha = .9, size = 1.5, shape = 1) +
  
  scale_color_manual(values = c("firebrick", # coloring
                                "royalblue3",
                                "lightpink",
                                "lightblue3",
                                "grey80"),
                     breaks = c("up_adjp.05",
                                "down_adjp.05",
                                "up_adjp.1",
                                "down_adjp.1"),
                     labels = c("\U2191 (adj.p <.05)",
                                "\U2193 (adj.p <.05)",
                                "\U2191 (adj.p <.1)",
                                "\U2193 (adj.p <.1)")) +
  
  geom_text_repel(max.overlaps = 27, size = 3, # gene text on points
                  color = "grey10") + 
  
  # NUM SIG UP & DOWN! | use sep df, overwise overplots
  geom_text(data = sig_volcano_sum_no_litter, # up 
            aes(label = paste0(sig_no_up_lab, " \U2191")),
            x = 1.78, y = 9.7, size = 4, color = "firebrick") + 
  geom_text(data = sig_volcano_sum_no_litter, # down
            aes(label = paste0(sig_no_down_lab, " \U2193")),
            x = -1.78, y = 9.7, size = 4, color = "royalblue3") + 

  xlim(-2,2) +
  ylim(0,10) +
  facet_wrap(~Label, ncol = 3) + 
  facet_wrap(~Label, ncol = 3) + 
  
  labs(x = "log2FC",
       y = "-Log10(adj.p value)",
       color = "Protein Regulation") +
  
  geom_hline(yintercept = -log10(0.05),
             linetype = "dotted", linewidth = 0.1,
             color = "grey30") +
  
  geom_hline(yintercept = -log10(0.1),linetype = "dotted",
             linewidth = 0.1, color = "grey50") +

  geom_vline(xintercept = c(0),linetype = "solid",
             linewidth = 0.1, color = "grey80") +
  
  guides(color=guide_legend(nrow=1, byrow=TRUE)) +
  
  theme_bw() +
  theme(legend.position = "bottom",
        axis.title = element_text(color = "grey10", size = 10.5),
        legend.title = element_text(color = "grey10", size = 10.5),
        strip.text = element_text(size = 11.5, color = "grey10"),
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_line(color = "grey95"),
        panel.spacing.y = unit(0.75, "cm"), # vert spacing
        legend.margin = margin(-10,0,-10,0),  # space between plot & legend
        legend.key.size = unit(1, "cm"), # size of legend key icon
        )

big_volcano_no_lit
```

### Lit

```{r}
# make new df for the geom_text bit below.
# prev had from 1 df but over plots repeately & cant index since mapped_comp huge.
sig_volcano_sum_lit <- com_df_mapped %>%
  # filter(pairwise_comp == "litter") %>%
  filter(Label %in% c("S328 vs S329", "S328 vs S324", "S324 vs S422", "S426 vs S420",
               "S422 vs S423", "S329 vs S423", "S426 vs S423", "S420 vs S422")) %>%
  dplyr::select(Label, sig_no_up_lab, sig_no_down_lab) %>%
  unique() 
```

```{r}
big_volcano_lit <- com_df_mapped %>%
   filter(Label %in% c("S328 vs S329", "S328 vs S324", "S324 vs S422", "S426 vs S420",
                   "S422 vs S423", "S329 vs S423", "S426 vs S423", "S420 vs S422")) %>%
  ggplot(aes(x = log2FC, y = -log10(adj.pvalue), label = sig_g_label)) +
  # POINTS
  geom_point(aes(color = case_when( # conditional ass for color mapping
    adj.pvalue < 0.05 & log2FC > 0 ~ "up_adjp.05", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "down_adjp.05", # down sig .05
    adj.pvalue < 0.1 & log2FC > 0 ~ "up_adjp.1", # up 0.1
    adj.pvalue < 0.1 & log2FC < 0 ~ "down_adjp.1", # down .1
    TRUE ~ "ns" )), # catch the rest
    alpha = .9, size = 1.3, shape = 1) +
  
  scale_color_manual(values = c("firebrick", # coloring
                                "royalblue3",
                                "lightpink",
                                "lightblue3",
                                "grey80"),
                     breaks = c("up_adjp.05",
                                "down_adjp.05",
                                "up_adjp.1",
                                "down_adjp.1"),
                     labels = c("\U2191 (adj.p <.05)",
                                "\U2193 (adj.p <.05)",
                                "\U2191 (adj.p <.1)",
                                "\U2193 (adj.p <.1)")) +
  geom_text_repel(max.overlaps = 25, size = 2.8, # gene text on points
                  color = "grey15", min.segment.length = 1) + 
  # NUM SIG UP & DOWN! | use sep df, overwise overplots
  geom_text(data = sig_volcano_sum_lit, # up 
            aes(label = paste0(sig_no_up_lab, " \U2191")),
            x = 1.75, y = 9.6, size = 3.7, color = "firebrick") + 
  geom_text(data = sig_volcano_sum_lit, # down
            aes(label = paste0(sig_no_down_lab, " \U2193")),
            x = -1.75, y = 9.6, size = 3.7, color = "royalblue3") + 
  xlim(-2,2) +
  ylim(0,10) +
  facet_wrap(~Label, ncol = 4) + 
  facet_wrap(~Label, ncol = 4) + 
  labs(x = "log2FC",
       y = "-Log10(adj.p value)",
       color = "Protein Regulation") +
  geom_hline(yintercept = -log10(0.05),
             linetype = "dotted", linewidth = 0.1,
             color = "grey30") +
  geom_hline(yintercept = -log10(0.1),linetype = "dotted",
             linewidth = 0.1, color = "grey50") +
  geom_vline(xintercept = c(0),linetype = "solid",
             linewidth = 0.1, color = "grey80") +
  guides(color=guide_legend(nrow=1, byrow=TRUE)) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title = element_text(color = "grey10", size = 10.5),
        legend.title = element_text(color = "grey10", size = 10.5),
        strip.text = element_text(size = 10, color = "grey10"),
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_line(color = "grey95"),
        legend.margin = margin(-10,0,0,0),  # space between plot & legend
        legend.key.size = unit(1, "cm"), # size of legend key icon
        )

big_volcano_lit
```

```{r}
plot_grid(big_volcano_lit, big_volcano_no_lit, ncol = 1, rel_heights = c(0.7,1))

# DOES NOT WORK - MANULA EXPORT WITH DEVICE PIXEL RATIO OFF WORKS BEST SO FAR. 

# ggsave("output/2026_02_20_mss_sp_v3.1.2_volcanos_p5_cowplot_600dpi.png",
#        width = 900, height = 1000, units = "px",
#        dpi = 600)

# png("output/2026_02_20_mss_sp_v3.1.2_volcanos_p5_cowplot_600dpi.png",
#     # width = 700, height = 850, units = "px",
#     type = "cairo-png",
#     res = 300)
# 
# print(p)
# dev.off()


# 2026_02_20 - final version happy with NVM
# 2026_02_20_mss_sp_v3.1.2_volcanos_p8_cowplot_redo_925x1150
# eehhh stil kinda blurry....


# OMG ACTUALLY This works. just set size in viewer... | OK FINAL one acutally...
ggsave("2026_02_20_mss_sp_v3.1.2_volcanos_p9_cowplot_devoff_200dpi.png", dpi = 200)
```
