---
title: "MssTMT_Vis_2026_01_v3.2.2_1pspg_EExAge"
output: html_document
---

## Setup

```{r}
#load packages
library(tidyverse)
library(pheatmap)
library(msigdbr)
library(cowplot)
library(ggh4x) # scalenested
library(gt)
library(ggrepel) #  for geom_text_repel()
library(colorspace)
library(RColorBrewer)
library(paletteer)
library(ggnewscale) # additional color/fill scale new_scale_fill()
library(ggvenn) # vennys (old ones)
library(pcaMethods) # for various pca()
library(readxl)
```

### Load in data

```{r}
#psum
<<<<<<< HEAD
load("input/results/psum/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_psum.rda") # laptop

#load("input/MSstatsTMT/psum/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_psum.rda") # Jen

#comp
load("input/results/comp/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_comp.rda") # laptop
#load("input/MSstatsTMT/comp/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_comp.rda") # Jen
=======
#load("input/results/psum/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_psum.rda") # laptop
load("input/MSstatsTMT/psum/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_psum.rda") # Jen

#comp
#load("input/results/comp/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_comp.rda") # laptop
load("input/MSstatsTMT/comp/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_comp.rda") # Jen
>>>>>>> fba15644f685ef0c8096b113714ff3d9147c96bf

#anno
anno <- read_csv("input/anno/EEv&SH_F&M_TMT_anno_v3_df_b_check_sorted_2025_12_31.csv") 
# double check later!
```

### Map/Fix names

```{r}
# map details & shorten name
mapped_psum <- left_join(mapped_psum_v3.2.2_EExAge,
                                       anno,
                                       by = join_by(
                                         BioReplicate == BioReplicate,
                                         Mixture == Mixture,
                                         Channel == Channel)) %>%
  dplyr::rename(Condition = Condition.x , Housing_c_anno = Condition.y) %>%
  mutate(Age = ifelse(PND > 100, "OLD", "YNG"))
  
#Check 
colnames(mapped_psum)
```

```{r}
# lil checks
head(mapped_comp_v3.2.2_EExAge_t1) # peak
str(mapped_comp_v3.2.2_EExAge_t1) # structure 
colnames(mapped_comp_v3.2.2_EExAge_t1) # column names
dim(mapped_comp_v3.2.2_EExAge_t1) # 64392 x 8

# lil checks (bit messy)
unique(mapped_comp_v3.2.2_EExAge_t1$issue) # na in issue col = good. if not excl
check_1 <- mapped_comp_v3.2.2_EExAge_t1 %>%
  filter(str_detect(log2FC, "Inf")) # 5 inf 
check_2 <- mapped_comp_v3.2.2_EExAge_t1 %>%
  filter(str_detect(Protein, "Cont")) # 0 (since already removed)
unique(mapped_comp_v3.2.2_EExAge_t1$Label) 
length(unique(mapped_comp_v3.2.2_EExAge_t1$Label)) #8
```

```{r}
# shorten name & clean up! 
mapped_comp <- mapped_comp_v3.2.2_EExAge_t1 %>%
  
  filter(is.na(issue)) %>% # keeps rows with issue == na (so comps that are ok)
  filter(!str_detect(log2FC, "Inf")) %>% # remove infinity/missing FC values
  
  # make gene label for significant! 
  mutate(sig_g_label = if_else(adj.pvalue <= .1, gene, NA)) %>%
  
  # make one for no of sig up & down for each comaprison group/label
  group_by(Label) %>%
  mutate(sig_no_up_lab = sum(adj.pvalue < 0.05 & log2FC > 0), # up
         sig_no_down_lab = sum(adj.pvalue < 0.05 & log2FC < 0)) %>%  #  down
  
  mutate(Direction = ifelse(log2FC > 0, "Up", "Down"))

# check 
head(mapped_comp) 
colnames(mapped_comp)
dim(mapped_comp) # 64384 x 22

unique_check <- mapped_comp %>% 
  dplyr::select(Label, sig_no_down_lab, sig_no_up_lab) %>%
  unique() # yep matches up! 
```

```{r}
mapped_comp_sig <- mapped_comp %>%
  filter(adj.pvalue < 0.05)

dim(mapped_comp_sig) # 458 x 21
```

# Plotting Comp

```{r}
my_theme <- theme(
    axis.line = element_blank(),
    axis.title = element_text(size = 10, color = "grey10"), 
    # axis.title.x = element_blank(),
    axis.text = element_text(size = 7.5, color ="grey10"),
    axis.ticks = element_line(size=0.5, colour = "grey15"),
    axis.ticks.length.y.left = unit(-0.1, 'cm'), # inwards ticks (L)
    axis.ticks.length.y.right = unit(-0.07, 'cm'), # inwards ticks (R)
    panel.background = element_rect(fill = "white"), #bg of plot (inner bit)
    panel.border = element_rect(fill = NA,
                                color = "grey10"), #plot borders
    plot.background = element_rect(fill = "white"), # bg of plot (outer)
    panel.grid = element_blank(),
    panel.spacing = unit(0, "cm"),  # Removes space between panel 
    legend.position = 'bottom',
    legend.title = element_text(size = 9, face="italic", color = "grey10"),
    legend.margin = margin(-5,0,0,0), # space between plot & legend
    #legend.title.align = (0.5), # centres legend title
    legend.text = element_text(size = 8.5, color = "grey10"),
    legend.box = "horizontal", 
    legend.direction = "horizontal", 
    legend.key.size = unit(0.5, "cm"), # size of legend key icon
    strip.background = element_rect(color = 'grey10', fill = 'grey90'), 
    strip.text.x = element_text(size = 9, color = 'grey10',
                                margin = margin(b = 3, t = 2)) #vert spacing
  )

```

# General QC Plots

## Heatmap

<https://biostatsquid.com/step-by-step-heatmap-tutorial-with-pheatmap/>

```{r}
# matrix df for heatmap &  PCAs
heatmap_matrix <- mapped_psum %>%
  mutate(comb_name = paste0(BioReplicate, " - ", Mixture, " - ", Channel)) %>%
  group_by(comb_name, Protein) %>%
  summarise(meanAbundance = mean(Abundance, na.rm = TRUE)) %>% # rm na 2 plot
  dplyr::select(Protein, meanAbundance, comb_name) %>%
  pivot_wider(names_from = comb_name,
              values_from = meanAbundance) %>%
  tidyr::drop_na() %>%
  tibble::column_to_rownames("Protein") %>% # set Accession to rowname
  as.matrix()
```

```{r}
heatmap_1 <- pheatmap(heatmap_matrix,
                      main = "QC Check - Mean Abundance Across Samples (55/56)",
                      show_rownames =  FALSE, # rms overplotted protein names
                      fontsize_col = 9)
# exported as 2026_01_19_pheatmap_QC_check_mean_abund_rm129_outlier_v1
# basic QC
```

### PCA

-   see pg 5 of doc & MSstatsTMT_2025_10_v3.1.6_plots.Rmd - <https://www.bioconductor.org/packages/release/bioc/html/pcaMethods.html>

```{r}
# PCA MATRIX - basically the same as above... 
pca_matrix <- mapped_psum  %>%
  mutate(rcbr = paste0(Run, '_', Channel, '_', BioReplicate), .after = Channel) %>%
  dplyr::select(rcbr, Protein, Abundance) %>%
  pivot_wider(names_from = rcbr,
              values_from = Abundance) %>%
  tidyr::drop_na() %>%
  tibble::column_to_rownames("Protein") %>%
  as.matrix()

dim(pca_matrix) # 3767 x 165
```

```{r}
# prep labeling with the rcbr col
prots_anno <- mapped_psum %>%
  mutate(rcbr = paste0(Run, '_', Channel, '_', BioReplicate), .after = Channel) %>%
  dplyr::select(Mixture:rcbr, BioReplicate, Condition, Year:Age) %>%
  unique()

rownames(prots_anno) <- prots_anno$rcbr # needed for by = 0 in merge to work
dim(prots_anno)
```

```{r}
# swap dir or prot & samples 
pca_cc <- pca(t(pca_matrix)) # transposed (so 55 scores)

# Do this way instead. for some reason the doing it directly results
pca_scores_cc <- scores(pca_cc)

merged_pca_cc <- merge(prots_anno, pca_scores_cc, by = 0) # row names set for by = 0 

ggplot(merged_pca_cc,
       aes(x = PC1, y = PC2,
           color = Mixture,
           fill = Housing,
           label = rcbr)) +
  geom_point(shape = 21, size =2, alpha = 0.7) +
  geom_text_repel() +
  scale_fill_manual(values = c("#66A61EFF", "#E6AB02FF")) + # housing colors 
  scale_color_manual(values = c("#d5a6bd", "#9fc5e8",
                             "#ea9999", "#f9cb9c")) +
  labs(title = "129N B1 removed (55/56)",
       subtitle = "MssTMT_Vis_2026_01_v3.2.2_1pspg_EExAge") +
  stat_ellipse() +
  theme_bw()

# exp 9 x 9 - not much of a difference between rm & non rm.
#2026_01_19_mss_v3.2.2_PCA_plot_rm_129N_B1_55_v1 
# plot is a big ugly?
```

------------------------------------------------------------------------

## Volcano

-   Big Volcano - When doing all -\> Error in UseMethod("depth") : no applicable method for 'depth' applied to an object of class "NULL (takes 10 years on laptop) ➝ due to geom_text_repel() trying to plot the ns ones ➝ fixed if make a just sig gene/protein column

-   Should have just made a function..... oh well do later.

```{r}
# make new df for the geom_text bit below.
# prev had from 1 df but over plots repeately & cant index since mapped_comp huge.
sig_volcano_sum <- mapped_comp %>%
  dplyr::select(Label, sig_no_up_lab, sig_no_down_lab) %>%
  unique()

# reoder factor levels for plotting
mapped_comp$Label <- factor(
  mapped_comp$Label,
    levels = c(
      "H_EE_vs_SH", "A_YNG_vs_OLD",
      "HxA_EE_YNG_vs_SH_YNG", "HxA_EE_YNG_vs_EE_OLD",
      "HxA_EE_OLD_vs_SH_OLD", "HxA_SH_YNG_vs_SH_OLD",
      "HxA_EE_YNG_vs_SH_OLD", "HxA_EE_OLD_vs_SH_YNG"
      ))
```

```{r}
# unique(mapped_comp$Label)
# unicodes for up \U2191 & down \U2193
big_volcano <- mapped_comp %>%
  
  
  # filter((Label %in% c("HxA_EE_YNG_vs_SH_YNG"))) %>%

  
  ggplot(aes(x = log2FC, y = -log10(adj.pvalue), label = sig_g_label)) +
  
  
  # POINTS
  geom_point(aes(color = case_when( # conditional ass for color mapping
    adj.pvalue < 0.05 & log2FC > 0 ~ "up_adjp.05", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "down_adjp.05", # down sig .05
    adj.pvalue < 0.1 & log2FC > 0 ~ "up_adjp.1", # up 0.1
    adj.pvalue < 0.1 & log2FC < 0 ~ "down_adjp.1", # down .1
    TRUE ~ "ns" )), # catch the rest
    alpha = .9, size = 1, shape = 1) +
  
  scale_color_manual(values = c("firebrick", # coloring
                                "royalblue3",
                                "lightpink",
                                "lightblue3",
                                "grey80"),
                     breaks = c("up_adjp.05",
                                "down_adjp.05",
                                "up_adjp.1",
                                "down_adjp.1"),
                     labels = c("\U2191 (adj.p <.05)",
                                "\U2193 (adj.p <.05)",
                                "\U2191 (adj.p <.1)",
                                "\U2193 (adj.p <.1)")) +
  
  geom_text_repel(max.overlaps = 30, size = 2, # gene text on points
                  color = "grey10") + 
  
  
  # NUM SIG UP & DOWN! | use sep df, overwise overplots
  geom_text(data = sig_volcano_sum, # up 
            aes(label = paste0(sig_no_up_lab, " \U2191")),
            x = 1.8, y = 7.4, size = 3.5, color = "firebrick"
            ) + 
  geom_text(data = sig_volcano_sum, # down
            aes(label = paste0(sig_no_down_lab, " \U2193")),
            x = -1.8, y = 7.4, size = 3.5, color = "royalblue3"
            ) + 

  xlim(-2,2) +
  facet_wrap(~Label, ncol = 4) + 
  facet_wrap(~Label, ncol = 4) + 
  
  labs(x = "log2FC",
       y = "-Log10(adj.p value)",
       color = "Protein Regulation") +
  
  geom_hline(yintercept = -log10(0.05),
             linetype = "dotted", linewidth = 0.1,
             color = "grey30") +
  # annotate("text", x = 1.95, y = -log10(0.05),
  #          label = "adj.p <.05 \n",
  #          fontface = 'italic', size = 1.5, color = "grey10") +
  
  geom_hline(yintercept = -log10(0.1),linetype = "dotted",
             linewidth = 0.1, color = "grey50") +
  # annotate("text", x = 1.95, y = -log10(0.1),
  #          label = " adj.p <.1 \n",
  #          fontface = 'italic', size = 1.5, color = "grey30") +
  
  geom_vline(xintercept = c(0),linetype = "solid",
             linewidth = 0.1, color = "grey80") +
  
  guides(color=guide_legend(nrow=1, byrow=TRUE)) +
  
  theme_bw() +
  theme(legend.position = "bottom",
        axis.title = element_text(color = "grey10", size = 10),
        legend.title = element_text(color = "grey10", size = 10),
        strip.text = element_text(size = 9, color = "grey10"),
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_line(color = "grey95"),
        legend.margin = margin(-10,0,0,0),  # space between plot & legend
        legend.key.size = unit(1, "cm"), # size of legend key icon
        )

big_volcano
  
# exported 4 x 2 mini version just for overview   10.5 x 6 inches pdf 
# 2026_01_17_EExAge_8_volcanos_4x2_mini_v2 | 10.5 x 6 inches pdf 
# 2026_01_17_EExAge_8_volcanos_4x2_mini_v3 | 10.5 x 6 inches pdf (fixed name)
```

### EE Volcanos

```{r}
EE_Volcano <- mapped_comp %>%
  
  filter(Label == "H_EE_vs_SH") %>%
  
    ggplot(aes(x = log2FC, y = -log10(adj.pvalue), label = sig_g_label,
               alpha = adj.pvalue)) +
  
  
  # POINTS
  geom_point(aes(color = case_when( # conditional ass for color mapping
    adj.pvalue < 0.05 & log2FC > 0 ~ "up_adjp.05", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "down_adjp.05", # down sig .05
    adj.pvalue < 0.1 & log2FC > 0 ~ "up_adjp.1", # up 0.1
    adj.pvalue < 0.1 & log2FC < 0 ~ "down_adjp.1", # down .1
    TRUE ~ "ns" )), # catch the rest
     size = 2.5, shape = 1, stroke = 1) +
  
  scale_color_manual(values = c("firebrick", # coloring
                                "royalblue3",
                                "pink3",
                                "lightblue3",
                                "grey90"),
                     breaks = c("up_adjp.05",
                                "down_adjp.05",
                                "up_adjp.1",
                                "down_adjp.1"),
                     labels = c("\U2191 (adj.p <.05)", 
                                "\U2193 (adj.p <.05)",
                                "\U2191 (adj.p <.1)",
                                "\U2193 (adj.p <.1)")) +
  
  geom_text_repel(max.overlaps = 30, size = 3.5, # gene text on points
                  color = "grey10", alpha = 1 ) + 
  

  scale_alpha_continuous(range = c(1, .2), # rev, smaller p = higher
                         guide = 'none') + 
  


  xlim(-1,1) +
  # facet_wrap(~Label, scales = "free_y") +
  facet_wrap(~Label, ncol = 4) +
  
  labs(x = "log2FC",
       y = "-Log10(adj.p value)",
       color = "Protein Regulation") +
  
  geom_hline(yintercept = -log10(0.05),
             linetype = "solid", linewidth = 0.01,
             color = "grey60") +
  annotate("text", x = .95, y = -log10(0.05),
           label = "adj.p <.05 \n",
           fontface = 'italic', size = 3, color = "grey40") +
  
  geom_hline(yintercept = -log10(0.1),linetype = "solid",
             linewidth = 0.01, color = "grey70") +
  annotate("text", x = .95, y = -log10(0.1),
           label = " adj.p <.1 \n",
           fontface = 'italic', size = 3, color = "grey50") +
  
  geom_vline(xintercept = c(0),linetype = "solid",
             linewidth = 0.01, color = "grey80") +
  
  guides(color=guide_legend(nrow=1, byrow=TRUE)) +
  
  my_theme +
  theme(
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_line(color = "grey95"),
        legend.margin = margin(-10,0,0,0),  # space between plot & legend
        legend.key.size = unit(1, "cm"), # size of legend key icon
  )

EE_Volcano
```

```{r}
EE_Volcano_age <- mapped_comp %>%
  
  filter(Label %in% c("HxA_EE_YNG_vs_SH_YNG", "HxA_EE_OLD_vs_SH_OLD" )) %>%
  
    ggplot(aes(x = log2FC, y = -log10(adj.pvalue), label = sig_g_label,
               alpha = adj.pvalue)) +
  
  
  # POINTS
  geom_point(aes(color = case_when( # conditional ass for color mapping
    adj.pvalue < 0.05 & log2FC > 0 ~ "up_adjp.05", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "down_adjp.05", # down sig .05
    adj.pvalue < 0.1 & log2FC > 0 ~ "up_adjp.1", # up 0.1
    adj.pvalue < 0.1 & log2FC < 0 ~ "down_adjp.1", # down .1
    TRUE ~ "ns" )), # catch the rest
     size = 2.5, shape = 1, stroke = 1) +
  
  scale_color_manual(values = c("firebrick", # coloring
                                "royalblue3",
                                "pink3",
                                "lightblue3",
                                "grey90"),
                     breaks = c("up_adjp.05",
                                "down_adjp.05",
                                "up_adjp.1",
                                "down_adjp.1"),
                     labels = c("\U2191 (adj.p <.05)",
                                "\U2193 (adj.p <.05)",
                                "\U2191 (adj.p <.1)",
                                "\U2193 (adj.p <.1)")) +
  
  geom_text_repel(max.overlaps = 30, size = 3.5, # gene text on points
                  color = "grey10", alpha = 1 ) + 
  
  scale_alpha_continuous(range = c(1, .2), # rev, smaller p = higher
                         guide = 'none') + 
  


  xlim(-1,1) +
  # facet_wrap(~Label, scales = "free_y") +
  facet_wrap(~Label, ncol = 1) +
  
  labs(x = "log2FC",
       y = "-Log10(adj.p value)",
       color = "Protein Regulation") +
  
  geom_hline(yintercept = -log10(0.05),
             linetype = "solid", linewidth = 0.01,
             color = "grey60") +
  annotate("text", x = .90, y = -log10(0.05),
           label = "adj.p <.05 \n",
           fontface = 'italic', size = 2, color = "grey40") +
  
  geom_hline(yintercept = -log10(0.1),linetype = "solid",
             linewidth = 0.01, color = "grey70") +
  annotate("text", x = .90, y = -log10(0.1),
           label = " adj.p <.1 \n",
           fontface = 'italic', size = 2, color = "grey50") +
  
  geom_vline(xintercept = c(0),linetype = "solid",
             linewidth = 0.01, color = "grey80") +
  
  guides(color=guide_legend(nrow=1, byrow=TRUE)) +
  
  my_theme +
  theme(legend.position = 'none',
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_line(color = "grey95"),

        )

EE_Volcano_age
```

```{r}
#cowplot
plot_grid(EE_Volcano, EE_Volcano_age, ncol = 2,
          rel_widths = c(2,1))
#2026_01_18_EEcomps_3_volcanos_cowplot_v1 exp 9.5 x 6 ?
```

### Age

```{r}
Age_Volcano <- mapped_comp %>%
  
  filter(Label == "A_YNG_vs_OLD") %>%
  
    ggplot(aes(x = log2FC, y = -log10(adj.pvalue), label = sig_g_label,
               alpha = adj.pvalue)) +
  
  
  # POINTS
  geom_point(aes(color = case_when( # conditional ass for color mapping
    adj.pvalue < 0.05 & log2FC > 0 ~ "up_adjp.05", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "down_adjp.05", # down sig .05
    adj.pvalue < 0.1 & log2FC > 0 ~ "up_adjp.1", # up 0.1
    adj.pvalue < 0.1 & log2FC < 0 ~ "down_adjp.1", # down .1
    TRUE ~ "ns" )), # catch the rest
     size = 2.3, shape = 1, stroke = 1) +
  
  scale_color_manual(values = c("firebrick", # coloring
                                "royalblue3",
                                "pink3",
                                "lightblue3",
                                "grey90"),
                     breaks = c("up_adjp.05",
                                "down_adjp.05",
                                "up_adjp.1",
                                "down_adjp.1"),
                     labels = c("\U2191 (adj.p <.05)",
                                "\U2193 (adj.p <.05)",
                                "\U2191 (adj.p <.1)",
                                "\U2193 (adj.p <.1)")) +
  
  geom_text_repel(max.overlaps = 30, size = 3.3, # gene text on points
                  color = "grey10", alpha = 1 ) + 
  
  scale_alpha_continuous(range = c(1, .15), # rev, smaller p = higher
                         guide = 'none') + 
  


  xlim(-2,2) +
  # facet_wrap(~Label, scales = "free_y") +
  facet_wrap(~Label, ncol = 4) +
  
  labs(x = "log2FC",
       y = "-Log10(adj.p value)",
       color = "Protein Regulation") +
  
  geom_hline(yintercept = -log10(0.05),
             linetype = "solid", linewidth = 0.01,
             color = "grey60") +
  annotate("text", x = 1.96, y = -log10(0.05),
           label = "adj.p <.05 \n",
           fontface = 'italic', size = 3, color = "grey40") +
  
  geom_hline(yintercept = -log10(0.1),linetype = "solid",
             linewidth = 0.01, color = "grey70") +
  annotate("text", x = 1.96, y = -log10(0.1),
           label = " adj.p <.1 \n",
           fontface = 'italic', size = 3, color = "grey50") +
  
  geom_vline(xintercept = c(0),linetype = "solid",
             linewidth = 0.01, color = "grey80") +
  
  guides(color=guide_legend(nrow=1, byrow=TRUE)) +
  
  my_theme +
  theme(
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_line(color = "grey95"),
        legend.margin = margin(-10,0,0,0),  # space between plot & legend
        legend.key.size = unit(1, "cm"), # size of legend key icon
  )

Age_Volcano
```

```{r}
Age_Volcano_H <- mapped_comp %>%
  
  filter(Label %in% c("HxA_EE_YNG_vs_EE_OLD", "HxA_SH_YNG_vs_SH_OLD" )) %>%
  
    ggplot(aes(x = log2FC, y = -log10(adj.pvalue), label = sig_g_label,
               alpha = adj.pvalue)) +
  
  
  # POINTS
  geom_point(aes(color = case_when( # conditional ass for color mapping
    adj.pvalue < 0.05 & log2FC > 0 ~ "up_adjp.05", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "down_adjp.05", # down sig .05
    adj.pvalue < 0.1 & log2FC > 0 ~ "up_adjp.1", # up 0.1
    adj.pvalue < 0.1 & log2FC < 0 ~ "down_adjp.1", # down .1
    TRUE ~ "ns" )), # catch the rest
     size = 2.2, shape = 1, stroke = 1) +
  
  scale_color_manual(values = c("firebrick", # coloring
                                "royalblue3",
                                "pink3",
                                "lightblue3",
                                "grey90"),
                     breaks = c("up_adjp.05",
                                "down_adjp.05",
                                "up_adjp.1",
                                "down_adjp.1"),
                     labels = c("\U2191 (adj.p <.05)",
                                "\U2193 (adj.p <.05)",
                                "\U2191 (adj.p <.1)",
                                "\U2193 (adj.p <.1)")) +
  
  geom_text_repel(max.overlaps = 30, size = 3.3, # gene text on points
                  color = "grey10", alpha = 1 ) + 
  
  scale_alpha_continuous(range = c(1, .15), # rev, smaller p = higher
                         guide = 'none') + 
  


  xlim(-2,2) +
  # facet_wrap(~Label, scales = "free_y") +
  facet_wrap(~Label, ncol = 1) +
  
  labs(x = "log2FC",
       y = "-Log10(adj.p value)",
       color = "Protein Regulation") +
  
  geom_hline(yintercept = -log10(0.05),
             linetype = "solid", linewidth = 0.01,
             color = "grey60") +
  annotate("text", x = 1.9, y = -log10(0.05),
           label = "adj.p <.05 \n",
           fontface = 'italic', size = 2, color = "grey40") +
  
  geom_hline(yintercept = -log10(0.1),linetype = "solid",
             linewidth = 0.01, color = "grey70") +
  annotate("text", x = 1.9, y = -log10(0.1),
           label = " adj.p <.1 \n",
           fontface = 'italic', size = 2, color = "grey50") +
  
  geom_vline(xintercept = c(0),linetype = "solid",
             linewidth = 0.01, color = "grey80") +
  
  guides(color=guide_legend(nrow=1, byrow=TRUE)) +
  
  my_theme +
  theme(legend.position = 'none',
        panel.grid.major = element_line(color = "grey90"),
        panel.grid.minor = element_line(color = "grey95"),

        )

Age_Volcano_H
```

```{r}
# cowplot
plot_grid(Age_Volcano, Age_Volcano_H, ncol = 2,
          rel_widths = c(2,1))
#2026_01_18_Agecomps_3_volcanos_cowplot_v1 exp 9.5 x 6 
```

------------------------------------------------------------------------

# psumplots

mt theme

#### Colors

```{r}
# COLOR BLIND FRIENDLY COLORS
palette.colors() #Okabe-Ito 9 - discrete colors
palette.colors(10, recycle = TRUE) #Recycles 1st to get 10
hcl.colors(9, palette = "Purple-Green") # seq/div (continuous)
hcl.colors(8, palette = "Blues 3") # seq/div (continuous)
palette.pals() # prints all available 
palette("Tableau 10")

# colorspace hcl
colorspace::swatchplot(qualitative_hcl(5, palette = "Dark 3")) #
colorspace::hclplot(diverging_hcl(10, palette = "Lisbon")) # multicolors
hcl_palettes("sequential (multi-hue)", n = 7, plot = TRUE)
qualitative_hcl(4, palette = "Dark 3")
divergingx_palettes(n = 7, plot = TRUE)
# colorspace::specplot()

# paleteer
paletteer_d("nord::aurora")

display.brewer.all() #RColorBrewer

# Paletteer prints hexcode with color in console!!!! 
paletteer_d("RColorBrewer::RdYlGn")
paletteer_d("RColorBrewer::Spectral")
paletteer_d("RColorBrewer::PiYG")
paletteer_d("RColorBrewer::BrBG")
paletteer_d("RColorBrewer::Pastel2")
paletteer_d("RColorBrewer::Dark2")
paletteer_d("rcartocolor::Temps")
paletteer_d("rcartocolor::Geyser")
paletteer_d("rcartocolor::Sunset")
paletteer_d("rcartocolor::Emrld")
paletteer_d("rcartocolor::OrYel")
```

EE vs SH

-   <https://stats.oarc.ucla.edu/r/modules/subsetting-data/>

<!-- -->

-   <https://en.wikipedia.org/wiki/List_of_Crayola_crayon_colors>

```{r}
colors <- c("#8CB585","#A8D9A0", "#D4C07E", "#FEE697", "#E6AB02FF",
            "#66A61EFF" )
# Banana Mania (#FBE7B2), Sunglow (#FFCC33), 	Dandelion (#FED85D)
# Maximum Green (#5E8C31)| Asparagus #7BA05B, Middle Green Yellow (#ACBF60)
```

### For Loops & Functions

Function for boxplots

-   <https://github.com/eliocamp/ggnewscale?tab=readme-ov-file>

```{r}
boxplot_function <- function(data, x , y, # function inputs
                             fill = Housing,
                             # alpha = NULL,
                             shape_color = TechRepMixture,
                             shape_fill = NULL,
                             facet_formula = ~Age+Cohort+Litter+Sex , # default
                             legend_pos = "bottom", 
                             title = NULL, # need to set as NULL?
                             subtitle = NULL) {
  
  #set up polot ^ assign 2 p
  p <- ggplot(data, aes({{x}},{{y}},
              # color = {{color}},
              # shape = {{shape}},
              # alpha = {{alpha}}
              )) +
    
    # make box plot
    geom_boxplot(aes(fill = {{fill}}),
                 width = 0.55, size = 0.7, median.linewidth = 1, linewidth = 0.2,
                 position = position_dodge(width = 0.7),
                 outlier.shape = NA,
                 color = "grey10", alpha = 0.7) +
    
    stat_summary(fun=mean, geom="point", position = position_dodge(width = 0.7),
               shape=4, size = .8, stroke = 0.2, color ="grey10") + #displays mean 
    
    # scale_alpha_discrete(guide = 'none', range = c(0.65, 0.75)) +
    scale_fill_manual(values = c("#66A61EFF", "#E6AB02FF")) + # housing colors 
    # scale_shape_manual(values = c(1, 3, 4)) + # techreplicate (3)
    

    # New SCALE with NEW GEOM 
    ggnewscale::new_scale_fill() +
      geom_point(aes(fill = {{shape_fill}}, color = {{shape_color}}),
      size = 1, shape = 21, stroke = .1, 
      position = position_jitterdodge(dodge.width = 0.4, jitter.width = 0.02)) +
    #2nd scale
    scale_color_manual(values = c("#003a6d","#31135e","#510224")) + # IBM
    scale_fill_manual(values = alpha(c("#eee8d5", "#b58900", "#C06A0B", "#cb4b16",
                                       "#D43F23", "#dc322f", "#D83459", "#d33682",
                                       "#A054A3", "#6c71c4", "#497ECB", "#268bd2",
                                       "#2896B5", "#2aa198", "#589D4C", "#859900",
                                       "#586e75"), 0.5)) + # solarised mix
    
    
    # FACET
    ggh4x::facet_nested(facet_formula) +
    
    labs(title = title, subtitle = subtitle) + # TITLE & SUBTITLE
    
    guides(color = "none",
           fill = guide_legend(nrow=1, byrow=TRUE)) +
    
    # theme (maybe just add theme from above or beeter self contained like this?)
    theme(
    plot.title = element_text(size = 10.5, color = "grey10"),
    plot.subtitle = element_text(size = 9, color = "grey10", face = "italic"),
    axis.line = element_blank(),
    axis.title = element_text(size = 9, color = "grey10"), 
    axis.text = element_text(size = 7.5, color ="grey10"),
    axis.ticks = element_line(size=0.1, colour = "grey15", linewidth = .1),
    
    panel.background = element_rect(fill = "white"), #bg of plot (inner)
    
    panel.border = element_rect(fill = NA, linewidth = .1,
                                color = "grey10"), #plot borders
    plot.background = element_rect(fill = "white"), # bg of plot (outer)
    panel.grid = element_blank(),
    panel.spacing = unit(0, "cm"),  # Removes space between panel 
    
    legend.position = legend_pos, # LEGEND POSITON
    
    legend.title = element_text(size = 9, face="italic", color = "grey10"),
    legend.margin = margin(-5,0,0,0), # space between plot & legend
    #legend.title.align = (0.5), # centres legend title
    legend.text = element_text(size = 8.5, color = "grey10"),
    legend.box = "horizontal", 
    legend.direction = "horizontal", 
    legend.key.size = unit(0.5, "cm"), # size of legend key icon
    strip.background = element_rect(color = 'grey10', fill = 'grey90',
                                    linewidth = .1), 
    strip.text.x = element_text(size = 8.5, color = 'grey10',
                                margin = margin(b = 2, t = 1.5)) #vert spacing
  )
    
}
```

Testing Function! - Yep works!

```{r}
# Synaptopodin
Synpo <- mapped_psum %>%
  filter(Protein %in% c("Q9Z327")) # 

Synpo_plot <- boxplot_function(Synpo, 
                       x = Housing, 
                       y = Abundance,
                       fill = Housing,  # by default
                       # color = interaction(BioReplicate, TechRepMixture),
                       shape_fill = Channel,
                       shape_color = TechRepMixture,
                       # alpha = Age,
                       legend_pos = "none",
                       title = 'Q9Z327 - Synaptopodin',
                       subtitle = '(Synpo) - In all 55 Samples')

Synpo_plot

unique(Synpo$BioReplicate)
unique(Synpo$`Gene Names (primary)`) #Synpo
length(unique(Synpo$BioReplicate)) # 56 observations! 55

Synpo %>% 
  group_by(TechRepMixture) %>%
  count(TechRepMixture)
```

------------------------------------------------------------------------

### For Housing per protein

```{r}
EE_main_sig_df <- mapped_comp %>%
  filter(Label == "H_EE_vs_SH" & adj.pvalue < 0.05) %>%
  group_by(Direction) %>%
  arrange(adj.pvalue)


EE_main_p_sig_list <- unique(EE_main_sig_df$Protein)

EE_main_psum_plot_list <- vector(mode = "list")
```

```{r}
for (p in EE_main_p_sig_list){
  
  #OPERATIONS
  #SET UP/CALC
  bp_df <- mapped_psum %>% #from psums
  filter(Protein == p) 
  
  
  bp_labs <- EE_main_sig_df %>% # using the filter mapped_comp list 
    filter(Protein == p) %>%
    dplyr::slice(1) 
  
  obs_in <- mapped_psum %>% #get no. biorep observed
  filter(Protein == p) %>%
    summarise(n_unique = n_distinct(BioReplicate)) %>%
    pull(n_unique)
  
  
  
  # MAKE PLOT
  bp <- boxplot_function( 
       data = bp_df,
       x = Housing, 
       y = Abundance,
       fill = Housing,  # by default
       shape_fill = Channel, #de
       shape_color = TechRepMixture,
       legend_pos = "none", # default
       title = paste0(bp_labs$gene, " - ", bp_labs$description),
       subtitle = paste0(bp_labs$Direction, "regulated in EE (",
                         bp_labs$uniprot_acc, " ", bp_labs$database,
                         " - observed in ", obs_in, " samples)"
                         )
       )
  
  print(bp)

  
  # SAVIHG PLOTS
    if (bp_labs$Direction[1] == "Up") {
      EE_main_psum_plot_list$Up[[p]] <- bp

    } else{
      EE_main_psum_plot_list$Down[[p]] <- bp
    }


  
}
```

Save list of plots

```{r}
save()
```

#### cowplots

saved everything for EE sig (16 prots)

```{r}
# get 5 at a time
plot_grid(plotlist = EE_main_psum_plot_list$Down[1:5], ncol = 1)
```

```{r}
plot_grid(plotlist = EE_main_psum_plot_list$Up, ncol = 1)
# maybe need to export again, a bit squished
```

```{r}
# FINISH HERE!!!
# EE_psum_facet <- mapped_psum %>%
#   filter(protein_existence)
```

------------------------------------------------------------------------

### For Age

```{r}
top_20_sig_Age_df <- mapped_comp %>%
  filter(Label == "A_YNG_vs_OLD" & adj.pvalue <0.05) %>%
  group_by(Direction) %>%
  arrange(adj.pvalue)%>%
  slice_min(adj.pvalue, n = 10)


Age_main_p_sig_list <- unique(top_20_sig_Age$Protein)

Age_main_20_psum_plot_list <- vector(mode = "list")
```

```{r}
for (p in Age_main_p_sig_list){
  
  #OPERATIONS
  # SET UP/ CALC
  bp_df <- mapped_psum %>% #from psums
  filter(Protein == p) 
  
  
  bp_labs <- top_20_sig_Age_df %>% # using the filter mapped_comp list 
    filter(Protein == p) %>%
    slice(1) 
  
  
  obs_in <- mapped_psum %>% #get no. biorep observed
  filter(Protein == p) %>%
    summarise(n_unique = n_distinct(BioReplicate)) %>%
    pull(n_unique)
  
  # MAKE PLOT
  bp <- boxplot_function( 
       data = bp_df,
       x = Housing, 
       y = Abundance,
       fill = Housing,  # by default
       shape_fill = Channel, #de
       shape_color = TechRepMixture,
       legend_pos = "none", # default
       title = paste0(bp_labs$gene, " - ", bp_labs$description),
       subtitle = paste0(bp_labs$Direction, "regulated in YNG (",
                         bp_labs$uniprot_acc, " ", bp_labs$database,
                         " - observed in ", obs_in, " samples)"
                         )
       )
  
  print(bp)

  
  # SAVIHG PLOTS
    if (bp_labs$Direction[1] == "Up") {
      Age_main_20_psum_plot_list$Up[[p]] <- bp

    } else{
      Age_main_20_psum_plot_list$Down[[p]] <- bp
    }


  
}
```

```{r}
# cowplot = DOWN IN AGE (YNG)
plot_grid(plotlist = Age_main_20_psum_plot_list$Down, ncol = 2)
```

```{r}
# cowplot = UP IN AGE (YNG)
plot_grid(plotlist = Age_main_20_psum_plot_list$Up, ncol = 2)
```

```{r}
plot_grid(plotlist = Age_main_20_psum_plot_list$Down[6:10], ncol = 1)
```

```{r}
plot_grid(plotlist = Age_main_20_psum_plot_list$Up[6:10], ncol = 1)
```

------------------------------------------------------------------------

### EE FACET

```{r}
boxplot_function_facet <- function(data, x , y, # function inputs
                             fill = Housing,
                             # alpha = NULL,
                             shape_color = TechRepMixture,
                             shape_fill = NULL,
                             facet_formula = ~Age+Cohort+Litter+Sex , # default
                             legend_pos = "bottom", 
                             title = NULL, # need to set as NULL?
                             subtitle = NULL) {
  
  #set up polot ^ assign 2 p
  p <- ggplot(data, aes({{x}},{{y}},
              )) +
    
    # make box plot
    geom_boxplot(aes(fill = {{fill}}),
                 width = 0.55, size = 0.7, median.linewidth = 0.5, linewidth = 0.2,
                 position = position_dodge(width = 0.7),
                 outlier.shape = NA,
                 color = "grey10", alpha = 0.7) +
    
    stat_summary(fun=mean, geom="point", position = position_dodge(width = 0.7),
               shape=4, size = .8, stroke = 0.2, color ="grey10") + #displays mean 
    
    # scale_alpha_discrete(guide = 'none', range = c(0.65, 0.75)) +
    # scale_fill_manual(values = c("#66A61EFF", "#E6AB02FF")) + # housing colors 
    
   scale_fill_manual(
     values = alpha(c("#B3D38F", "#F3D581"), 0.3)) + # housing colors 
    # scale_shape_manual(values = c(1, 3, 4)) + # techreplicate (3)
    

    # New SCALE with NEW GEOM 
    ggnewscale::new_scale_fill() +
      geom_point(aes(fill = {{shape_fill}}, color = {{shape_color}}),
      size = 1, shape = 21, stroke = .1, 
      position = position_jitterdodge(dodge.width = 0.4, jitter.width = 0.02)) +
    #2nd scale
    scale_color_manual(values = c("#003a6d","#31135e","#510224")) + # IBM
    scale_fill_manual(values = alpha(c("#eee8d5", "#b58900", "#C06A0B", "#cb4b16",
                                       "#D43F23", "#dc322f", "#D83459", "#d33682",
                                       "#A054A3", "#6c71c4", "#497ECB", "#268bd2",
                                       "#2896B5", "#2aa198", "#589D4C", "#859900",
                                       "#586e75"), 0.5)) + # solarised mix
    
    
    # FACET
    ggh4x::facet_nested(facet_formula) +
    
    labs(title = title, subtitle = subtitle) + # TITLE & SUBTITLE
    
    guides(color = "none",
           fill = guide_legend(nrow=1, byrow=TRUE)) +
    
    # theme (maybe just add theme from above or beeter self contained like this?)
    theme(
    plot.title = element_text(size = 10.5, color = "grey10"),
    plot.subtitle = element_text(size = 9, color = "grey10", face = "italic"),
    axis.line = element_blank(),
    axis.title = element_text(size = 9, color = "grey10"), 
    axis.text = element_text(size = 7.5, color ="grey10"),
    axis.ticks = element_line(size=0.1, colour = "grey15", linewidth = .1),
    
    panel.background = element_rect(fill = "white"), #bg of plot (inner)
    
    panel.border = element_rect(fill = NA, linewidth = .2,
                                color = "grey10"), #plot borders
    plot.background = element_rect(fill = "white"), # bg of plot (outer)
    panel.grid = element_blank(),
    panel.spacing = unit(0, "cm"),  # Removes space between panel 
    
    legend.position = legend_pos, # LEGEND POSITON
    
    legend.title = element_text(size = 9, face="italic", color = "grey10"),
    legend.margin = margin(-5,0,0,0), # space between plot & legend
    #legend.title.align = (0.5), # centres legend title
    legend.text = element_text(size = 8.5, color = "grey10"),
    legend.box = "horizontal", 
    legend.direction = "horizontal", 
    legend.key.size = unit(0.5, "cm"), # size of legend key icon
    strip.background = element_rect(color = 'grey10', fill = 'grey90',
                                    linewidth = .2), 
    strip.text.x = element_text(size = 8.5, color = 'grey10',
                                margin = margin(b = 2, t = 1.5)) #vert spacing
  )
    
}
```

```{r}
# EE UP
EE_facet_up_prot_list <- mapped_comp %>%
  filter(Label == "H_EE_vs_SH" & adj.pvalue < 0.05 & Direction == "Up") %>%
    pull(Protein)

  
EE_facet_up_plot <- mapped_psum %>%
  
  mutate(Condition = forcats::fct_reorder(Condition, PND)) %>% # reoder by PND (no)
  
  
  filter(Protein %in% EE_facet_up_prot_list) %>%
  
  
  
  ggplot(aes(x = interaction(Age, Housing, 
                             sep = "\n", # space
                             lex.order = TRUE),
             y = Abundance,
             fill = Housing, alpha = Age)) +
  geom_boxplot(width = 0.45, size = 0.7, median.linewidth = 1, linewidth = 0.2,
                 position = position_dodge(width = 0.7),
                 outlier.shape = NA,
                 color = "grey10") +
  stat_summary(fun=mean, geom="point", position = position_dodge(width = 0.7),
               shape=4, size = .8, stroke = 0.2, color ="grey10") +
  geom_point(color = "grey10", size = 0.6, shape = 1, stroke = .1, 
      position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.3)) +
  
  scale_fill_manual(values = c("#66A61EFF", "#E6AB02FF")) + # housing colors
  scale_alpha_manual(values = c(.6,.75)) +
  scale_color_manual(values = c("#003a6d", "#31135e")) +
  # guides(y.sec = 'axis') + # adds 2nd y axis (right side)
  facet_wrap(~gene, ncol = 6, scale = "free_y") +
  my_theme +
  theme(
     axis.text.y = element_text(size = 7.5, color ="grey10"),
     axis.text.x = element_text(size = 7, color ="grey10"),
     axis.title.x = element_blank(),
     panel.spacing = unit(0.2, "cm"),  # Removes space between panel 
     legend.margin = margin(,0,20,0), # space between plot & legend
     axis.ticks = element_line(size=0.1, colour = "grey15", linewidth = .01),
         panel.border = element_rect(fill = NA, linewidth = .01,
                                color = "grey10"), #plot borders
         strip.background = element_rect(color = 'grey10', fill = 'grey90',
                                    linewidth = .01), 
  )
  

EE_facet_up_plot
```

```{r}
# EE down
EE_facet_down_prot_list <- mapped_comp %>%
  filter(Label == "H_EE_vs_SH" & adj.pvalue < 0.05 & Direction == "Down") %>%
  arrange(adj.pvalue) %>%
  pull(Protein)

  
EE_facet_down_plot <- mapped_psum %>%
  
  mutate(Condition = forcats::fct_reorder(Condition, PND)) %>% # reoder by PND (no)
  
  filter(Protein %in% EE_facet_down_prot_list) %>%
  
  mutate(gene = ifelse(Protein == "Q5U2Q3", "NA (Ester hydrolase ...)",
                       gene)) %>%
  
  ggplot(aes(x = interaction(Age, Housing, 
                             sep = "\n", # space
                             lex.order = TRUE),
             y = Abundance,
             fill = Housing, alpha = Age)) +
  geom_boxplot(width = 0.5, size = 0.6, median.linewidth = 1, linewidth = 0.2,
                 position = position_dodge(width = 0.7),
                 outlier.shape = NA,
                 color = "grey10") +
  stat_summary(fun=mean, geom="point", position = position_dodge(width = 0.7),
               shape=4, size = .8, stroke = 0.2, color ="grey10") +
  geom_point(color = "grey10", size = 0.7, shape = 1, stroke = .1, 
      position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.3)) +
  
  scale_fill_manual(values = c("#66A61EFF", "#E6AB02FF")) + # housing colors
  scale_alpha_manual(values = c(.6,.75)) +
  scale_color_manual(values = c("#003a6d", "#31135e")) +
  # guides(y.sec = 'axis') + # adds 2nd y axis (right side)
  facet_wrap(~gene, ncol = 5, scales = "free_y") +
  my_theme +
  theme(
     axis.text.y = element_text(size = 7.5, color ="grey10"),
     axis.text.x = element_text(size = 7, color ="grey10"),
     axis.title.x = element_blank(),
      panel.spacing = unit(0.9, "cm"),  # Removes space between panel 
        legend.margin = margin(0,0,0,0), # space between plot & legend
          axis.ticks = element_line(size=0.1, colour = "grey15", linewidth = .01),
         panel.border = element_rect(fill = NA, linewidth = .01,
                                color = "grey10"), #plot borders
         strip.background = element_rect(color = 'grey10', fill = 'grey90',
                                    linewidth = .01), 
  )
  

EE_facet_down_plot
```

```{r}
plot_grid(EE_facet_up_plot,EE_facet_down_plot, ncol = 1,
          labels = c("A", "B"), rel_heights = c(1.15,2))
```

### AGE FACET

```{r}
# AGE UP
Age_facet_up_prot_list <- mapped_comp %>%
  filter(Label == "A_YNG_vs_OLD" & adj.pvalue < 0.05 & Direction == "Up") %>%
    slice_min(adj.pvalue, n = 18) %>%
    pull(Protein)

  
Age_facet_up_plot <- mapped_psum %>%
  
  mutate(Condition = forcats::fct_reorder(Condition, PND)) %>% # reoder by PND (no)
  
  
  filter(Protein %in% Age_facet_up_prot_list) %>%
  
  
  ggplot(aes(x = interaction(Age, Housing, 
                             sep = "\n", # space
                             lex.order = TRUE),
             y = Abundance,
             fill = Housing, alpha = Age)) +
  geom_boxplot(width = 0.5, size = 0.7, median.linewidth = 1, linewidth = 0.2,
                 position = position_dodge(width = 0.7),
                 outlier.shape = NA,
                 color = "grey10") +
  stat_summary(fun=mean, geom="point", position = position_dodge(width = 0.7),
               shape=4, size = .8, stroke = 0.2, color ="grey10") +
  geom_point(color = "grey10", size = .5, shape = 1, stroke = .1, 
      position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.3)) +
  
  scale_fill_manual(values = c("#66A61EFF", "#E6AB02FF")) + # housing colors
  scale_alpha_manual(values = c(.6,.75)) +
  scale_color_manual(values = c("#003a6d", "#31135e")) +
  # guides(y.sec = 'axis') + # adds 2nd y axis (right side)
  facet_wrap(~gene, ncol = 6, scale = "free_y") +
  my_theme +
  theme(
     axis.text.y = element_text(size = 7.5, color ="grey10"),
     axis.text.x = element_text(size = 7, color ="grey10"),
     axis.title.x = element_blank(),
     panel.spacing = unit(0.2, "cm"),  # Removes space between panel 
     legend.margin = margin(0,0,5,0), # space between plot & legend
     axis.ticks = element_line(size=0.1, colour = "grey15", linewidth = .01),
         panel.border = element_rect(fill = NA, linewidth = .01,
                                color = "grey10"), #plot borders
         strip.background = element_rect(color = 'grey10', fill = 'grey90',
                                    linewidth = .01), 
  )
  

Age_facet_up_plot
```

```{r}
# AGE Down
Age_facet_down_prot_list <- mapped_comp %>%
  filter(Label == "A_YNG_vs_OLD" & adj.pvalue < 0.05 & Direction == "Down") %>%
    slice_min(adj.pvalue, n = 18) %>%
    pull(Protein)


Age_facet_down_plot <- mapped_psum %>%
  
  mutate(Condition = forcats::fct_reorder(Condition, PND)) %>% # reoder by PND (no)
  
  
  filter(Protein %in% Age_facet_down_prot_list) %>%

  
  
  
  ggplot(aes(x = interaction(Age, Housing, 
                             sep = "\n", # space
                             lex.order = TRUE),
             y = Abundance,
             fill = Housing, alpha = Age)) +
  geom_boxplot(width = 0.5, size = 0.7, median.linewidth = 1, linewidth = 0.2,
                 position = position_dodge(width = 0.7),
                 outlier.shape = NA,
                 color = "grey10") +
  stat_summary(fun=mean, geom="point", position = position_dodge(width = 0.7),
               shape=4, size = .8, stroke = 0.2, color ="grey10") +
  geom_point(color = "grey10", size = .5, shape = 1, stroke = .1, 
      position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.3)) +
  
  scale_fill_manual(values = c("#66A61EFF", "#E6AB02FF")) + # housing colors
  scale_alpha_manual(values = c(.6,.75)) +
  scale_color_manual(values = c("#003a6d", "#31135e")) +
  # guides(y.sec = 'axis') + # adds 2nd y axis (right side)
  facet_wrap(~gene, ncol = 6, scale = "free_y") +
  my_theme +
  theme(
     axis.text.y = element_text(size = 7.5, color ="grey10"),
     axis.text.x = element_text(size = 7, color ="grey10"),
     axis.title.x = element_blank(),
     panel.spacing = unit(0.2, "cm"),  # Removes space between panel 
     legend.margin = margin(0,0,0,0), # space between plot & legend
     axis.ticks = element_line(size=0.1, colour = "grey15", linewidth = .01),
         panel.border = element_rect(fill = NA, linewidth = .01,
                                color = "grey10"), #plot borders
         strip.background = element_rect(color = 'grey10', fill = 'grey90',
                                    linewidth = .01), 
  )
  

Age_facet_down_plot
```

```{r}
plot_grid(Age_facet_up_plot, Age_facet_down_plot, ncol = 1,
          labels = c("A", "B"))
```

## Venny's?

"Age specific differences in housing contribute to the effect driving but not age in itself!" This is reassuring!

```{r}
# from above 
# EE_main_p_sig_list
EE_main_p_sig_01_list <- 

Age_main_sig_list <- mapped_comp %>%
  filter(Label == "A_YNG_vs_OLD" & adj.pvalue <0.05) %>%
  pull(Protein)

# only "P85845" fascin! 
intersect(EE_main_p_sig_list, Age_main_sig_list)

# 
# venn_list <- list(Housing = EE_main_p_sig_list, Age = Age_main_sig_list)
```

```{r}
# TO FIX 
# ggvenn(c(EE_main_p_sig_list, Age_main_sig_list),
#          digits = 0, # 0 digits after decimal,
#          stroke_alpha = 0.7,
#          fill_alpha = 0.45,
#               stroke_size = 0.5,
#               set_name_size = 3.5,
#               text_size = 3.2)
```

# gt tables

"Age specific differences in housing contribute to the effect driving but not age in itself!" This is reassuring!

## All Significant (8 comp)

```{r}
mapped_comp_sig |> 
  
  
  dplyr::select(c(Label,Direction, gene, Protein, description, 
                  log2FC, adj.pvalue, database)) |>
  
  arrange(adj.pvalue) |>
  
  gt(
    groupname_col = "Label",
    rowname_col = "Direction"
  ) |>
  
  cols_label(
    
  ) |>
  
  fmt_number(decimals = 3) |>
  
  tab_header(
    title = "EE x Age (all 8 comparisons)",

  ) |>
  
  tab_style( 
    style = list(
      cell_text(size = 8)
      ),
    locations = cells_body(
      columns = c(description)
    )
  ) |>
  
  tab_options(table.font.size = 11)
  
  # tab_options(
  #   heading.title.font.size = 16.5,
  #             table.font.size=11.5,
  #             row_group.font.weight = "bold",
  #             row_group.font.size = 14,
  #             column_labels.font.size = 12.5,
  #             column_labels.font.weight = "bold") #|>
```

## EE Comps

```{r}
gt_1 <- mapped_comp %>%
  
  # filter(Label %in% c("H_EE_vs_SH",
  # "HxA_EE_YNG_vs_SH_YNG", "HxA_EE_OLD_vs_SH_OLD")) %>%
  
  filter(Label == "H_EE_vs_SH") %>%
  
  
  # filter(adj.pvalue < 0.05) %>% #
  filter(adj.pvalue < 0.5) %>% #


  dplyr::select(c(Label,Direction, gene, Protein, description, 
                  log2FC, adj.pvalue, , database, SE, DF, pvalue)) %>%
  
  arrange(adj.pvalue) %>%
  
  # slice_min(adj.pvalue,n=20) %>%
  
  gt(
    groupname_col = "Label",
    rowname_col = "Direction"
  ) %>%
  
  cols_label(
    gene = "Gene",
    # Uniprot_entry_name = "Name",
    description = "Protein Description",
    database = "db"
  ) %>%
  
  fmt_number(decimals = 3) %>%
  
  # tab_header(
  #   # title = "Proteins Differentially Regulated by Housing Condition",
  #   # subtitle = "This table is arranged from the smallest adj. p-value and is split by comparison label. For the main effect of housing, the 16 significant proteins (adj.p <.05) are shown, followed by an additional 9 (adj p <.05).",
  # ) %>%
  # 
  tab_style( 
    style = list(
      # cell_fill(color = "#F9E3D6"),
      cell_text(style = "italic")
      ),
    locations = cells_body(
      columns = gene,
      # rows = currency < 100
    )
  ) %>%
  
  tab_style( 
    style = list(
      # cell_fill(color = "#F9E3D6"),
      cell_text(size = 8)
      ),
    locations = cells_body(
      columns = c(description)
      # rows = currency < 100
    )
  ) %>%
  
  tab_options(
    #heading.title.font.size = 16.5,
              table.font.size=11,
              # table.font.style = "lighter",
              # stub.font.weight = "bold",
              # stub.font.size = 13,
              # row_group.font.weight = "italic",
              #row_group.font.size = 14,
              #column_labels.font.size = 12.5,
              # column_labels.font.weight = "bold"
              ) #|>

gt_1
```

```{r}
gt <- as_gtable(gt_1, plot = TRUE, text_grob = grid::textGrob)
```

------------------------------------------------------------------------

Exports

```{r}
#
# write_excel_csv(mapped_comp_sig, "output/2026_01_20_EExAge_mapped_comp_sig_458obs.csv")

#

```

```{r}

unique_g <- unique(mapped_comp$gene) %>% as.tibble()

# write_excel_csv(unique_g,
#                 "output/2026_01_20_EExAge_mapped_comp_unique_genes_8014.csv")
```

```{r}
# EE_main_df_all <- mapped_comp %>%
#   filter(Label == "H_EE_vs_SH") %>%
#   group_by(Direction) %>%
#   arrange(adj.pvalue)

# write_excel_csv(EE_main_df_all, "output/2026_01_20_ExA_EE_main_comp_mapped_8048.csv")
```

```{r}

```

------------------------------------------------------------------------

# 1 - Neurotrophic Signalling

one by one comparisons

```{r}
Housing_top_250 <- mapped_comp %>%
  # filter(Label %in% c("H_EE_vs_SH",
  # "HxA_EE_YNG_vs_SH_YNG", "HxA_EE_OLD_vs_SH_OLD")) %>%
  filter(Label == "H_EE_vs_SH") %>%
  slice_min(adj.pvalue, n = 250, with_ties = FALSE)


EE_main_only <- mapped_comp %>%
  filter(Label == "H_EE_vs_SH")

EE_main_sig_df_adjp01 <- EE_main_only %>%
  filter(adj.pvalue < 0.1)
```

```{r}
# import 
mice_lit_re <- read_excel("input/lit_review/2026_02_01_EE_omics_lit_review_mRNA_Proteins.xlsx",
           sheet = 'mice_proteins_mRNA')
```

#### Hu et al., 2013 Comparison

```{r}
Hu_2013 <- mice_lit_re %>%
  filter(Author == "Hu") %>%
  filter(is.na(Mod)) %>%
  mutate(Study = paste0(Author, " ", Year)) 

dim(Hu_2013) #15 x 31
```

```{r}
# No over lap in significant  
intersect(Hu_2013$Uniprot_rat_accession, EE_main_sig_df$Protein)

# in top 250 EE 
intersect(Hu_2013$Uniprot_rat_accession, Housing_top_250$Protein)

# in full 8000 list
intersect(Hu_2013$Uniprot_rat_accession, EE_main_only$Protein)

EE_Hu_overlap <- intersect(Hu_2013$Uniprot_rat_accession, EE_main_only$Protein)

EE_Hu_overlap_my_df <- left_join(Hu_2013, EE_main_only,
                            by = join_by(Uniprot_rat_accession == Protein)) 

EE_Hu_overlap_my_df <- EE_Hu_overlap_my_df  %>%
   mutate(Hu_2013 =  case_when(
    Significant == "yes" & In_EE == "Up" ~ "\u2191 *",
    Significant == "yes" & In_EE == "Down" ~ "\u2193 *",
    Significant == "no" & In_EE == "Up" ~ "\u2191",
    Significant == "no" & In_EE == "Down" ~ "\u2193",
    In_EE == "Same" ~ "-",
    .default = " "
   )) %>%
  mutate(EE_vs_SH = case_when(
    adj.pvalue < 0.05 & log2FC > .05 ~ "\u2191 *", # up sig .05
    adj.pvalue < 0.05 & log2FC < -.05 ~ "\u2193 *", # down sig .05
    pvalue.y < 0.05 & log2FC > .05 ~ "\u2191", # up sig .05
    pvalue.y < 0.05 & log2FC < -.05 ~ "\u2193", # down sig .05
    .default = "-"
  )) 

# %>%
#   
#   mutate(custom_label = case_when(
#     !is.na(Label) & !is.na(Mod) ~ Mod,
#      is.na(Label) & !is.na(Mod) ~ " ",
#     !is.na(Label) ~ Label
#   ))
#  


  # filter(if(any(Reviewed == "reviewed", na.rm = TRUE)) {
  #    Reviewed == "reviewed" # if reviewed = keep,
```

me_and_hu_gtg \<- as_gtable(me_and_hu_gt, plot = TRUE, text_grob = grid::textGrob)

```{r}
me_and_hu_gt <- EE_Hu_overlap_my_df %>%
  dplyr::ungroup() %>%
  dplyr::select(c(Label, Animal, Region, Exp_type,
                  Method, Used_name,
                 Gene_name, Full_name, 
                 Hu_2013, EE_vs_SH, log2FC, adj.pvalue)) %>%
  
 gt(
    groupname_col = "Label",
    rowname_col = "Gene_name"
  ) %>%
  
  fmt_number(decimals = 2)  %>%
  
    cols_label(
    Full_name = "Protein Description",
  ) %>%
  
  tab_source_note(source_note = "Comparison to Hu et al., 2013. Table does not include phosphoproteins.") %>%
  
  tab_style(
    style = list(
      cell_text(style = "italic")
      ),
    locations = cells_stub()) %>%
  
    tab_options(table.font.size=10) %>%
    opt_vertical_padding(scale = 0.5) %>% # vert padding
  
    tab_style( 
    style = list(
      # cell_fill(color = "#F9E3D6"),
      cell_text(weight = "bold", size = 16)
      ),
    locations = list(
      cells_column_labels(columns = c(Hu_2013, EE_vs_SH)),
      cells_body(columns = c(Hu_2013, EE_vs_SH))
      ))

  
me_and_hu_gt
  
me_and_hu_gtg <- as_gtable(me_and_hu_gt, plot = TRUE, text_grob = grid::textGrob)
```

```{r}
# Synaptopodin
TrkB <- mapped_psum %>%
  filter(Protein %in% c("Q63604")) # 

TrkB_plot <- boxplot_function(TrkB, 
                       x = Housing, 
                       y = Abundance,
                       fill = Housing,  # by default
                       # color = interaction(BioReplicate, TechRepMixture),
                       shape_fill = Channel,
                       shape_color = TechRepMixture,
                       # alpha = Age,
                       legend_pos = "none",
                       title = 'Q63604 - TrkB/Ntrk2 - ',
                       subtitle = '(TrKB/Ntrk2) - In all 55 Samples')

TrkB_plot

unique(TrkB$BioReplicate)
unique(TrkB$`Gene Names (primary)`) #Synpo
length(unique(TrkB$BioReplicate)) # 56 observations! 55

TrkB %>% 
  group_by(TechRepMixture) %>%
  count(TechRepMixture)
```

```{r}
ribo <- EE_main_only %>%
  filter(stringr::str_detect(description, pattern = "ribosom|elong"))
```

------------------------------------------------------------------------

TO DO LATER!!!

```{r}
UP_Paban_list <- c('Bdnf', 'Gmfb', 'Gdnf', 'Gfra3',
                   'Mt3', 'Ngf', 'Tac1', 'Npffr2', 'Fgf2',
                   'Ptn', 'Cxcr4', 'Myc', 'Stat5a')

Paban_pat <- paste(UP_Paban_list, collapse = "|") # so sep by OR |

me_and_paban <- EE_main_only %>%
  # match any case insenstitive
  filter(str_detect(gene, regex(Paban_pat, ignore_case = TRUE)))

# matched 8, all non sig, closest is Protachykinin-1 but mapping weird Tac1?
# old paper so need to remap genes! 
# NVM DOUBLE CHECK THIS IM VERY CONFUSED!!! 
```

------------------------------------------------------------------------

# SYNAPTIC CHANGES

```{r}
borg <- read_csv("input/lit_review/2025_12_15_Borgmeyer_2021_Hip_SJ_proteomics_lit_re_rats_v1.csv")
```

```{r}
# NOTE SOME REDUNDANCIES
borg_trm <- borg %>%
  group_by(Used_name, Gene_name) %>%
  dplyr::slice(1) %>%  # rm 3 209 tp 206
  dplyr::select(adj.pvalue, Year:misc) %>%
  rename(b_adj.pvalue = adj.pvalue)
```

```{r}
# com 2 sig - 1 protein P85845 - Fascin
intersect(borg_trm$Uniprot_rat_accession, EE_main_sig_df$Protein) 
intersect(borg_trm$Gene_name, EE_main_sig_df$gene) # SAME AS ABOVE

# 5 proteins - Hcn2 K/NA, Dhrs4, Fascin, neuritin, 	Rho GTPase-act prot 39
intersect(borg_trm$Uniprot_rat_accession, Housing_top_250$Protein)
intersect(borg_trm$Gene_name, Housing_top_250$gene)

# 5 proteins - Hcn2 K/NA, Dhrs4, Fascin, neuritin, 	Rho GTPase-act prot 39
borg_list <- intersect(borg_trm$Uniprot_rat_accession, EE_main_only$Protein)

# borg_map <- EE_main_only %>%
#   filter(Protein %in% borg_list)

borg_map <-mapped_comp %>%
  filter(Label == "H_EE_vs_SH") %>%
  filter(Protein %in% borg_list)
```

```{r}

borg_merge <- left_join(borg_trm, borg_map, 
                        by = join_by(Uniprot_rat_accession == Protein))


borg_merge <- borg_merge  %>%
   mutate(Borgmeyer_2021 =  case_when(
    Significant == "yes" & In_EE == "Up" ~ "\u2191 *",
    Significant == "yes" & In_EE == "Down" ~ "\u2193 *",
    Significant == "no" & In_EE == "Up" ~ "\u2191",
    Significant == "no" & In_EE == "Down" ~ "\u2193",
    In_EE == "Same" ~ "-",
    .default = " "
   )) %>%
  mutate(EE_vs_SH = case_when(
    adj.pvalue < 0.05 & log2FC > .05 ~ "\u2191 *", # up sig .05
    adj.pvalue < 0.05 & log2FC < -.05 ~ "\u2193 *", # down sig .05
    pvalue < 0.05 & log2FC > .05 ~ "\u2191", # up sig .05
    pvalue < 0.05 & log2FC < -.05 ~ "\u2193", # down sig .05
    .default = " " # ‐
  )) %>%
  mutate(Full_name = str_trunc(Full_name, 80)) %>%
  filter(!is.na(Label)) %>% 
  arrange(adj.pvalue, Gene_name) 

```

```{r}
me_and_borg <- head(borg_merge, 30) %>%
  dplyr::ungroup() %>%
  dplyr::select(c(Label, Animal, Region, Exp_type,
                 Gene_name, Full_name, b_adj.pvalue, Fold_change,
                 Borgmeyer_2021,
                 EE_vs_SH,
                 log2FC, adj.pvalue)) %>%
  
 gt(
    groupname_col = "Label",
    rowname_col = "Gene_name"
  ) %>%

  fmt_number(decimals = 2)  %>%
  
    cols_label(
    Full_name = "Protein Description",
    Fold_change = "log2FC",
    b_adj.pvalue = "adj.pvalue"
  ) %>%
  
  tab_source_note(source_note = "Comparison to Borgmeyer 2021. Mapped to significant proteins in EE mice (DDA LFQ Proteomics, Hippocampal Synaptic Junctions of Male Mice). Top 30 most significant mapped proteins depicted.") %>%

  tab_style(
    style = list(
      cell_text(style = "italic",  size = px(12))
      ),
    locations = cells_stub()) %>%

    tab_options(table.font.size=10) %>%
    opt_vertical_padding(scale = 0.55) %>% # vert padding

    tab_style(
    style = list(
      cell_text(weight = "bold", size = px(14), # pass through px to work! 
                align = "center")  
      ),
    locations = list(
      cells_body(columns = c(Borgmeyer_2021, EE_vs_SH))
      )) %>%
  
  tab_style(
    style = list(
      cell_text(weight = "bold", size = px(11))),
    locations = list(
      cells_column_labels(columns = c(Borgmeyer_2021, EE_vs_SH))
      )) %>%
  tab_style(
    style = list(
      cell_text(color = "grey15", size = px(9))),
    locations = list(
      cells_body(columns = c(Animal, Region, Exp_type))
      )) %>%
  
  as_gtable(plot = TRUE)

me_and_borg

# me_and_borg_gtg<- as_gtable(me_and_borg, plot = TRUE, text_grob = grid::textGrob)
```

```{r}
list_SynDiv <- c("Camk2a", "Dlg4", 'Gphn', 'Gad2')
```

```{r}
SynDiv <- mapped_comp %>%
  # filter(Label == "H_EE_vs_SH") %>%
    filter(Label == "HxA_EE_YNG_vs_SH_YNG") %>%
  filter(gene %in% c("Camk2a", "Dlg4", 'Gphn', 'Gad2', 'Mbp', 'Gfap', 'Syp',
                    'Syn2', 'Gria1', 'Gria2', 'Gria3', 'Gria4' ))
```

```{r}
<<<<<<< HEAD

=======
EE_syn_check <- mapped_psum %>%
  
  mutate(Condition = forcats::fct_reorder(Condition, PND)) %>% # reoder by PND (no)
  filter(gene %in% c("Dlg4", 'Syp', 'Gria1', 'Gria2', 'Gria3', 'Gria4', 'Fscn1', 'Nrn1',
                     'Shank1', 'Shank2', 'Shank3,', 'Gphn', 'Gad2', 'Mbp', 'Gfap', "Camk2a", 'Syn2',
                     'Syt12', 'Ntrk2', 'Homer1', 'Syngap1', 'Faah', 'Abhd6', 'Cnr1', 'Synpo', 'Arhgap39')) %>%

  ggplot(aes(x = interaction(Age, Housing,
                             sep = "\n", # space
                             lex.order = TRUE),
             y = Abundance,
             fill = Housing, alpha = Age)) +
  geom_boxplot(width = 0.45, size = 0.7, median.linewidth = .2, linewidth = 0.2,
                 position = position_dodge(width = 0.7),
                 outlier.shape = NA,
                 color = "grey10") +
  stat_summary(fun=mean, geom="point", position = position_dodge(width = 0.7),
               shape=4, size = .8, stroke = 0.2, color ="grey10") +
  geom_point(color = "grey10", size = .5, shape = 1, stroke = .5,
      position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.3)) +

  scale_fill_manual(values = c("#66A61EFF", "#E6AB02FF")) + # housing colors
  scale_alpha_manual(values = c(.6,.75)) +
  scale_color_manual(values = c("#003a6d", "#31135e")) +
  # guides(y.sec = 'axis') + # adds 2nd y axis (right side)
  facet_wrap(~gene, ncol = 6, scale = "free_y") +
  my_theme +
  theme(
     axis.text.y = element_text(size = 9, color ="grey10"),
     axis.text.x = element_text(size = 9, color ="grey10"),
     axis.title.x = element_blank(),
     panel.spacing = unit(0.2, "cm"),  # Removes space between panel
     legend.margin = margin(,0,0,0), # space between plot & legend
     axis.ticks = element_line(size=0.1, colour = "grey15", linewidth = .2),
         panel.border = element_rect(fill = NA, linewidth = .2,
                                color = "grey10"), #plot borders
         strip.background = element_rect(color = 'grey10', fill = 'grey90',
                                    linewidth = .2),
  )


EE_syn_check
>>>>>>> fba15644f685ef0c8096b113714ff3d9147c96bf
```

**AGE CHANGES**

```{r}
EE_check_down <- mapped_psum %>%
  
  mutate(Condition = forcats::fct_reorder(Condition, PND)) %>% # reoder by PND (no)
  filter(gene %in% c('Tle2', 'Coro6', 'Echdc2', 'Ebf4', 'Tmsb10', 'Stmn1',
                     'Camk2n2', 'Sbsn', 'Arx', 'Nap1l5', 'Cdh22', 'Ccdc136',
                     'Gng4', 'Myoc' , 'Dpp10')) %>%

  ggplot(aes(x = interaction(Age, Housing,
                             sep = "\n", # space
                             lex.order = TRUE),
             y = Abundance,
             fill = Housing, alpha = Age)) +
  geom_boxplot(width = 0.45, size = 0.7, median.linewidth = .2, linewidth = 0.2,
                 position = position_dodge(width = 0.7),
                 outlier.shape = NA,
                 color = "grey10") +
  stat_summary(fun=mean, geom="point", position = position_dodge(width = 0.7),
               shape=4, size = .8, stroke = 0.2, color ="grey10") +
  geom_point(color = "grey10", size = .5, shape = 1, stroke = .5,
      position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.3)) +

  scale_fill_manual(values = c("#66A61EFF", "#E6AB02FF")) + # housing colors
  scale_alpha_manual(values = c(.6,.75)) +
  scale_color_manual(values = c("#003a6d", "#31135e")) +
  # guides(y.sec = 'axis') + # adds 2nd y axis (right side)
  facet_wrap(~gene, ncol = 6, scale = "free_y") +
  my_theme +
  theme(
     axis.text.y = element_text(size = 9, color ="grey10"),
     axis.text.x = element_text(size = 9, color ="grey10"),
     axis.title.x = element_blank(),
     panel.spacing = unit(0.2, "cm"),  # Removes space between panel
     legend.margin = margin(,0,0,0), # space between plot & legend
     axis.ticks = element_line(size=0.1, colour = "grey15", linewidth = .2),
         panel.border = element_rect(fill = NA, linewidth = .2,
                                color = "grey10"), #plot borders
         strip.background = element_rect(color = 'grey10', fill = 'grey90',
                                    linewidth = .2),
  )


EE_check_down
```

```{r}
EE_check_down <- mapped_psum %>%
  
  mutate(Condition = forcats::fct_reorder(Condition, PND)) %>% # reoder by PND (no)
  filter(gene %in% c('Trpc6','Plk5','Lct','Aldh1a1','Bdnf','Iqgap2','Egr3',
                     'Sema5a','Sipa1l3','Pdyn','Lrrc10b','Dagla','Rasd1','Lingo3',
                     'Tanc1','Nptx2','Kif17','Klk8','Ptgs2','Bok','Fosb','Syt12')) %>%

  ggplot(aes(x = interaction(Age, Housing,
                             sep = "\n", # space
                             lex.order = TRUE),
             y = Abundance,
             fill = Housing, alpha = Age)) +
  geom_boxplot(width = 0.45, size = 0.7, median.linewidth = .2, linewidth = 0.2,
                 position = position_dodge(width = 0.7),
                 outlier.shape = NA,
                 color = "grey10") +
  stat_summary(fun=mean, geom="point", position = position_dodge(width = 0.7),
               shape=4, size = .8, stroke = 0.2, color ="grey10") +
  geom_point(color = "grey10", size = .5, shape = 1, stroke = .5,
      position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.3)) +

  scale_fill_manual(values = c("#66A61EFF", "#E6AB02FF")) + # housing colors
  scale_alpha_manual(values = c(.6,.75)) +
  scale_color_manual(values = c("#003a6d", "#31135e")) +
  # guides(y.sec = 'axis') + # adds 2nd y axis (right side)
  facet_wrap(~gene, ncol = 6, scale = "free_y") +
  my_theme +
  theme(
     axis.text.y = element_text(size = 9, color ="grey10"),
     axis.text.x = element_text(size = 9, color ="grey10"),
     axis.title.x = element_blank(),
     panel.spacing = unit(0.2, "cm"),  # Removes space between panel
     legend.margin = margin(,0,0,0), # space between plot & legend
     axis.ticks = element_line(size=0.1, colour = "grey15", linewidth = .2),
         panel.border = element_rect(fill = NA, linewidth = .2,
                                color = "grey10"), #plot borders
         strip.background = element_rect(color = 'grey10', fill = 'grey90',
                                    linewidth = .2),
  )


EE_check_down
```

```{r}
plot_grid(EE_check_up, EE_check_down, ncol = 1)
```

```{r}
# PErez
'Tle2',
'Coro6',
'Echdc2',
'Ebf4',
'Tmsb10',
'Stmn1',
'Camk2n2',
'Sbsn',
'Arx',
'Nap1l5',
'Cdh22',
'Ccdc136',
'Gng4',
'Myoc' ,
'Dpp10',

'Trpc6',
'Plk5',
'Lct',
'Aldh1a1',
'Bdnf',
'Iqgap2',
'Egr3',
'Sema5a',
'Sipa1l3',
'Pdyn',
'Lrrc10b',
'Dagla',
'Rasd1',
'Lingo3',
'Tanc1',
'Nptx2',
'Kif17',
'Klk8',
'Ptgs2',
'Bok'.
'Fosb',
'Syt12',
```

```{r}
# import 
Perez_prot <- read_csv("input/lit_review/2025_12_27_Perez_2024_proteomics_map_rat_combined_v1.csv")
```

```{r}
Perez_prot_sig <- Perez_prot %>%
  filter(adj.P.Val < 0.05) %>%
  filter(proteomics_id == "all") # 945 x 57


# 945 comp to > 8000 - observe => 8000 present 
intersect(Perez_prot_sig$Entry, EE_main_only$Protein)


# 36 of Perez's EE_all sig adp <0.05 seen in out top 250 
intersect(Perez_prot_sig$Entry, Housing_top_250$Protein)


# 6 of Perez's EE_all sig adp <0.05 seen in our 16 sig adj p<0.05! 
intersect(Perez_prot_sig$Entry, EE_main_sig_df$Protein)


# 7 of Perez's EE_all sig adp <0.05 seen in our 16 sig adj p<0.05! 
intersect(Perez_prot_sig$Entry, EE_main_sig_df_adjp01$Protein)
```
