---
title: "MssTMT_Vis_2026_02_uniprot_anno_tables"
author: "Stephanie Huang"
date: "2026-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- [ ] 2026_07_02 - check why no p-value for perez_transcriptomics? (protein sheet has everything but not the transcriptomics sheet, although significant & other metrics there - check lit_reivew exp sheet!

```{r}
#load packages
library(tidyverse)
library(gt)
library(readxl)
```

## Load Files

You can also embed plots, for example:

```{r}
#psum
load("input/MSstatsTMT/psum/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_psum.rda") 

#comp
load("input/MSstatsTMT/comp/2025_12_31_1pspg_v3.2.2_t1_EExAge_mapped_comp.rda") 

# uniprot rat ref proteome anno
load("input/db/rat_ref_proteome_2025_12_13_51872x295.rda")

#anno
anno <- read_csv("input/anno/EEv&SH_F&M_TMT_anno_v3_df_b_check_sorted_2025_12_31.csv") 
# double check later!

# import 
mice_lit_re <- read_excel(
  "input/lit_review/2026_01_13_EE_omics_lit_review_mRNA_Proteins.xlsx",
           sheet = 'mice_proteins_mRNA')

rat_lit_re <- read_excel(
  "input/lit_review/2026_01_13_EE_omics_lit_review_mRNA_Proteins.xlsx",
           sheet = 'rat_proteins_mRNA')
```

## Wrangle

```{r}
# trim uniprot ann
colnames(rat_ref_proteome_2025_12_13)

rat_ref_trm <- rat_ref_proteome_2025_12_13 %>%
  dplyr::select(Entry, Protein.families, Keywords,
  Subcellular.location..CC.,
  Activity.regulation, Catalytic.activity, Cofactor, Developmental.stage:Pathway,
  Gene.Names)
```

```{r}
# see lil checks in other vis folder - 
# shorten name & clean up! 
mapped_comp <- mapped_comp_v3.2.2_EExAge_t1 %>%
  
  filter(is.na(issue)) %>% # keeps rows with issue == na (so comps that are ok)
  filter(!str_detect(log2FC, "Inf")) %>% # remove infinity/missing FC values
  
  # make gene label for significant! 
  mutate(sig_g_label = if_else(adj.pvalue <= .1, gene, NA)) %>%
  
  # make one for no of sig up & down for each comaprison group/label
  group_by(Label) %>%
  mutate(sig_no_up_lab = sum(adj.pvalue < 0.05 & log2FC > 0), # up
         sig_no_down_lab = sum(adj.pvalue < 0.05 & log2FC < 0)) %>%  #  down
  
  mutate(Direction = if_else(log2FC > 0, "Up", "Down")) %>%
  mutate(Direction_2 = if_else(Direction == "Up", "\u2191", # up arrow
                               "\u2193")) %>% # else down arrow
  
  mutate(protein_existence = as.character(protein_existence)) # as char so no decimal
  
  

# # check 
# head(mapped_comp) 
# colnames(mapped_comp)
# dim(mapped_comp) # 64384 x 22
# 
# unique_check <- mapped_comp %>% 
#   dplyr::select(Label, sig_no_down_lab, sig_no_up_lab) %>%
#   unique() # yep matches up! 
```

## Significant Proteins Tables

```{r}
mapped_comp_2 <- mapped_comp %>%
  left_join(rat_ref_trm,
             by = join_by(Protein == Entry))
```

------------------------------------------------------------------------

# Lit tables

```{r}
EE_mapped_comp <- mapped_comp %>%
  filter(Label == "H_EE_vs_SH")
```

```{r}
EE_mapped_comp_adjp1 <- EE_mapped_comp %>%
  filter(adj.pvalue <= 0.1) %>%
  pull(gene)
```

```{r}
Age_mapped_comp_trm <-  mapped_comp %>%
  filter(Label == "A_YNG_vs_OLD") %>%
  select(Label, gene, log2FC, adj.pvalue) %>%
  rename_with( ~ paste0("A_", .x), everything()) # add prefix onto col names A_
```

# MANUAL CURATION

RAT

```{r}
# drop spacing rows & convery *** to pvalue numbers instead. 
unique(rat_lit_re$pvalue)

rat_lit_EE <- rat_lit_re %>%
  tidyr::drop_na(Year, Author) %>% # rm empty spacing rowsw
  rename(pvalue_old = pvalue) %>%
  mutate(pvalue =  as.numeric(case_when(
    pvalue_old == "*" ~ "0.049",
    pvalue_old == "**" ~ "0.00999",
    pvalue_old == "***" ~ "0.00099",
    .default = pvalue_old
  )), .after = pvalue_old) %>%
  relocate(pvalue_old, .before = Year) %>% # checked okay 
  mutate(misc = as.character(misc)) %>%
  select(Year:misc)  # checked okay & can drop 
```

### Zhang et al., 2024

```{r}
zhang <- read_csv(
  "input/lit_review/2025_12_13_Zhang_2024_mPFC_lit_re_mapped_w_rat_ID_v1.csv") %>%
    select(Year:misc) # 31/62
```

```{r}

```

# AUTO MAP

## BOTH

```{r}
perez_p <- read_excel("input/lit_review/2025_12_27_Perez_2024_proteomics_lit_review_all_v1.xlsx",
                    sheet = "combined") %>%
    select(Year:misc)  #31/74 x 6849


perez_p <- perez_p %>%
  filter(!is.na(Gene_name)) %>%
  filter(!is.na(Uniprot_rat_accession)) #6483 
```

```{r}
perez_t <- read_excel("input/lit_review/2025_12_27_Perez_2024_transcriptomics_lit_review_all_v1.xlsx",
                      sheet = "combined") %>%
  select(Year:misc) #31/74
```

## Proteomics

Lichti et al., 2014

```{r}
lichti <- read_csv(
  "input/lit_review/2025_12_12_Lichti_2014_rats_NAc_data_lit_review_v1.csv") %>%
  select(Year:misc) #31/55
```

### Arroyo et al., 2020

```{r}
arroyo <- read_csv("input/lit_review/2025_12_29_Arroyo_2020_pigs_proteomics_lit_review_sig_v1.csv") %>%
  select(Year:misc) # 31/55
```

### Borgmeyer et al 2021

```{r}
borg <- read_csv("input/lit_review/2025_12_15_Borgmeyer_2021_Hip_SJ_proteomics_lit_re_rats_v1.csv") %>%
  relocate(pvalue, .after = Significant) %>%
  select(Year:misc) # 31/76
```

## Transcriptomics

### Park et al., 2015

```{r}
park <- read_csv("input/lit_review/2025_12_17_Park_2015_mRNA_lit_review_EExAging_summed_v2.csv") %>%
   select(Year:misc) #31/54
```

------------------------------------------------------------------------

------------------------------------------------------------------------

# MERGE

```{r}
merged <- bind_rows(rat_lit_EE, lichti, arroyo, borg, park, perez_p, zhang) %>%
  filter(!is.na(Gene_name)) # removes empty gene name rows (unmapped ones)
```

```{r}
gene_counts <- merged %>%
  group_by(Gene_name) %>%
  count(Author)
```

```{r}
adjp_overlap <- merged %>%
  filter(Gene_name %in% EE_mapped_comp_adjp1)
```

```{r}
# PErez
 down <- c('Tle2',
'Coro6',
'Echdc2',
'Ebf4',
'Tmsb10',
'Stmn1',
'Camk2n2',
'Sbsn',
'Arx',
'Nap1l5',
'Cdh22',
'Ccdc136',
'Gng4',
'Myoc' ,
'Dpp10')

up <- c('Trpc6',
'Plk5',
'Lct',
'Aldh1a1',
'Bdnf',
'Iqgap2',
'Egr3',
'Sema5a',
'Sipa1l3',
'Pdyn',
'Lrrc10b',
'Dagla',
'Rasd1',
'Lingo3',
'Tanc1',
'Nptx2',
'Kif17',
'Klk8',
'Ptgs2',
'Bok',
'Fosb',
'Syt12')
```

```{r}

wassouf_DEG <- data.frame(Direction_w  = c(rep("Wassouf 2018 - Up \u2191 in EE (Hip - mRNA)", 22), rep("Wassouf 2018 - Down \u2193 in EE (Hip - mRNA)", 15)),
                            gene = c(up, down)) 

was <- EE_mapped_comp %>%
  filter(gene %in% c(up, down))

perez_was_p <- perez_p %>%
  filter(Gene_name %in% c(up, down)) %>%
  filter(Condition == "all") %>%
    mutate(protein_all =  case_when(
    # Significant == "yes" & In_EE == "up" ~ "\u2191 *", # OLD VERSION
    # Significant == "yes" & In_EE == "down" ~ "\u2193 *",
    # Significant == "no" & In_EE == "up" ~ "\u2191",
    # Significant == "no" & In_EE == "down" ~ "\u2193",
    # In_EE == "Same" ~ "-",
    pvalue < 0.05 & Fold_change > 0 ~ "\u2191 *", # up sig .05
    pvalue < 0.05 & Fold_change < 0 ~ "\u2193 *", # down sig .05
    pvalue <= 0.11 & Fold_change > 0 ~ "\u2191 .", # up sig .1
    pvalue <= 0.11 & Fold_change < 0 ~ "\u2193 .", # down sig .1
    pvalue <= 0.51 & Fold_change > 0 ~ "\u2191", # up (~p0.03-05)
    pvalue <= 0.51 & Fold_change < 0 ~ "\u2193", # down 
    In_EE == "Same" ~ "-"
    # .default = " "
   )) %>%
  select(Gene_name, protein_all)

perez_was_t <- perez_t %>%
  filter(Gene_name %in% c(up, down)) %>%
  filter(Condition == "all") %>%
  mutate(mRNA_all =  case_when( # why no p-value for perez_t?
    Significant == "yes" & In_EE == "up" ~ "\u2191 *",
    Significant == "yes" & In_EE == "down" ~ "\u2193 *",
    Significant == "no" & In_EE == "up" ~ "\u2191",
    Significant == "no" & In_EE == "down" ~ "\u2193",
    In_EE == "Same" ~ "-",
    # .default = " "
   )) %>%
  select(Gene_name, mRNA_all)
```

```{r}

perez_was_me <- left_join(wassouf_DEG,  perez_was_p, 
                          by = join_by(gene == Gene_name)) %>%
  left_join(perez_was_t, by = join_by(gene == Gene_name)) %>%
  
  
  left_join(was, by = join_by(gene == gene)) %>% # EE vs SH
    mutate(EE_vs_SH = case_when(
    adj.pvalue < 0.05 & log2FC > 0 ~ "\u2191 *", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "\u2193 *", # down sig .05
    adj.pvalue <= 0.5 & log2FC > 0 ~ "\u2191", # up sig .05
    adj.pvalue <= 0.5 & log2FC  < 0 ~ "\u2193", # down sig .05
    .default = " " # ‐
  )) %>%
  
  left_join(Age_mapped_comp_trm, by = join_by(gene == A_gene)) %>% # YNG vs OLD
      mutate(YNG_vs_OLD = case_when(
    A_adj.pvalue < 0.05 & A_log2FC > 0 ~ "\u2191 *", # up sig .05
    A_adj.pvalue < 0.05 & A_log2FC < 0 ~ "\u2193 *", # down sig .05
    A_adj.pvalue <= 0.5 & A_log2FC > 0 ~ "\u2191", # up sig .05
    A_adj.pvalue <= 0.5 & A_log2FC  < 0 ~ "\u2193", # down sig .05
    .default = " " # ‐
  )) %>%
  
  # mutate(Wassouf_direction = if_else(str_detect()))
  arrange(adj.pvalue) 
```

```{r}
perez_was_me_gt <- perez_was_me %>%
  dplyr::select(c(Direction_w, gene,
                  description,
                  mRNA_all, protein_all,
                 EE_vs_SH, log2FC, adj.pvalue, # EE vs SH data
                 YNG_vs_OLD, A_log2FC , A_adj.pvalue
                 )) %>%
  
 gt(
    groupname_col = "Direction_w",
    rowname_col = "gene"
  ) %>%

  fmt_number(decimals = 2)  %>%
  
    cols_label(
    # description = "Protein Description",
    EE_vs_SH = "EE",
    YNG_vs_OLD = "YNG",
    adj.pvalue = "adj.p") %>%
  
  tab_source_note(source_note = "Comparison to Park et al. 2015 - EE x Age SAGEseq Transcriptomics (Hippocampus; male mice). Of the 469 (59 in EE young & 410 in EE old) significant genes identified, 263 were successfully mapped onto proteins in the current dataset, with the top 30 most significant in the H_EE_vs_SH comparison shown here. ") %>%

  tab_style(
    style = list(
      cell_text(style = "italic",  size = px(12.5))
      ),
    locations = cells_stub()) %>%

    tab_options(table.font.size=11.5) %>%
    opt_vertical_padding(scale = 0.3) %>% # vert padding

    # tab_style(
    # style = list(
    #   cell_text(weight = "bold", size = px(14), # pass through px to work! 
    #             align = "center")  
    #   ),
    # locations = list(
    #   cells_body(columns = c(mRNA_all, protein_all, EE_vs_SH))
    #   )) %>%
  
  tab_style(
    style = list(
      cell_text(size = px(11.5), align = "center")),
    locations = list(
      cells_column_labels(columns = c(mRNA_all, protein_all, EE_vs_SH))
      )) %>%
  
  
  tab_spanner(label = "Perez_2024",
              columns = c(mRNA_all, protein_all))  %>%
  tab_spanner(label = "H_EE_vs_SH", columns = c(EE_vs_SH, log2FC, adj.pvalue)) %>%
  tab_spanner(label = "A_YNG_vs_OLD", columns = c(YNG_vs_OLD, A_log2FC,
                                                A_adj.pvalue)) %>%

  
tab_style( # ARROYO
    style = list(cell_fill(color = "#fddde6"),
                 cell_text(color = "#d33682")),
    locations = cells_body(rows = str_detect(mRNA_all,  "\u2191 *"),
                           columns = c(mRNA_all))) %>%
  tab_style( 
    style = list(cell_fill(color = "#DBECFC"),
                 cell_text(color = "#2380c1")),
    locations = cells_body(rows = str_detect(mRNA_all, "\u2193 *"),
                           columns = c(mRNA_all))) %>%
  
  
  tab_style( # ARROYO
    style = list(cell_fill(color = "#fddde6"),
                 cell_text(color = "#d33682")),
    locations = cells_body(rows = str_detect(protein_all,  "\u2191 *"),
                           columns = c(protein_all))) %>%
  tab_style( 
    style = list(cell_fill(color = "#DBECFC"),
                 cell_text(color = "#2380c1")),
    locations = cells_body(rows = str_detect(protein_all, "\u2193 *"),
                           columns = c(protein_all))) %>%
  
  
  
tab_style( # My COLUMN
    style = list(cell_fill(color = "#fddde6"),
                 cell_text(color = "#d33682")),
    locations = cells_body(rows =  adj.pvalue < 0.35 & log2FC > 0 ,
                           columns = c(EE_vs_SH, log2FC, adj.pvalue))) %>%
  tab_style( 
    style = list(cell_fill(color = "#DBECFC"),
                 cell_text(color = "#2380c1")),
    locations = cells_body(rows = adj.pvalue < 0.35 & log2FC < 0,
                           columns = c(EE_vs_SH, log2FC, adj.pvalue))) %>%
  
  tab_style( # My COLUMN
    style = list(cell_fill(color = "#FEEEF3"),
                 cell_text(color = "#d33682")),
 locations = cells_body(rows = adj.pvalue < 0.7 & adj.pvalue > 0.35 & log2FC > 0,
                           columns = c(EE_vs_SH, log2FC, adj.pvalue))) %>%
  tab_style( 
    style = list(cell_fill(color = "#EFF6FD"),
                 cell_text(color = "#2380c1")),
 locations = cells_body(rows = adj.pvalue < 0.7 & adj.pvalue > 0.35 & log2FC < 0,
                           columns = c(EE_vs_SH, log2FC, adj.pvalue))) %>%
  
 tab_style( # My COLUMN - very NON SIG - DIRECTIONAL COLOR
    style = list(cell_text(color = "#d33682")),
  locations = cells_body(rows = adj.pvalue > 0.7 & log2FC > 0 ,
                           columns = c(EE_vs_SH, log2FC, adj.pvalue))) %>%
  tab_style( 
    style = list(cell_text(color = "#2380c1")),
  locations = cells_body(rows = adj.pvalue > 0.7 & log2FC < 0,
                           columns = c(EE_vs_SH, log2FC, adj.pvalue)))

  
  
print(perez_was_me_gt)
```

------------------------------------------------------------------------

#### Better meth? - perez_was_me_2

- <https://tidyr.tidyverse.org/reference/pivot_wider.html#ref-examples>
- <https://gt.rstudio.com/reference/tab_spanner_delim.html>
- <https://stackoverflow.com/questions/79559857/conditionally-color-cells-based-on-different-column-in-gt>
- <https://thegraphcourses.org/courses/epirep/topics/enhancing-gt-tables/>
- <https://stackoverflow.com/questions/61435048/conditional-formatting-of-multiple-columns-in-gt-table?rq=3>

```{r}
was_2 <- mapped_comp %>%
  ungroup() %>% 
  filter(Label %in% c("H_EE_vs_SH", "A_YNG_vs_OLD")) %>%
  select(Protein:log2FC, adj.pvalue, description, gene) %>% # ! for pivot_wider
  filter(gene %in% c(up, down)) %>%
      mutate(Symbols = case_when(
    adj.pvalue < 0.05 & log2FC > 0 ~ "\u2191 *", # up sig .05
    adj.pvalue < 0.05 & log2FC < 0 ~ "\u2193 *", # down sig .05
    adj.pvalue <= 0.11 & log2FC > 0 ~ "\u2191 .", # up sig .1
    adj.pvalue <= 0.11 & log2FC  < 0 ~ "\u2193 .", # down sig .1
    adj.pvalue <= 0.51 & log2FC > 0 ~ "\u2191", # up (~p0.03-05)
    adj.pvalue <= 0.51 & log2FC  < 0 ~ "\u2193", # down 
    .default = " ")) %>%
  pivot_wider(names_from = Label,
              # names_sep = ".",
              values_from = c(Symbols, log2FC, adj.pvalue),
              names_glue = "{Label}.{.value}") # need this order for gt

perez_was_me_2 <- left_join(wassouf_DEG,  perez_was_p,
                          by = join_by(gene == Gene_name)) %>%
  left_join(perez_was_t, by = join_by(gene == Gene_name)) %>%

  left_join(was_2, by = join_by(gene == gene)) %>%

  arrange(H_EE_vs_SH.adj.pvalue)

colnames(perez_was_me_2)
```

```{r}
# temp - my colors
# new is Azure & Barbie pink
up_colors <- c("#d33682", "#fddde6", "#FEEEF3")
new_up_colors <- c("#d33682", "#DA1884", "#fddde6", "#FEEEF3", "#fccad8")
down_colors <- c("#2380c1", "#DBECFC" )
new_down_colors <- c("#0080FF", "#c9e2fa", "#C0DDF9", "#b7d8f8")
```

```{r}
perez_was_me_gt_2 <- perez_was_me_2 %>%
  dplyr::select(c(Direction_w, gene,
                  description,
                  mRNA_all, protein_all,
                # selection of order matters for tab_spanner_delim
                 H_EE_vs_SH.Symbols, H_EE_vs_SH.log2FC, H_EE_vs_SH.adj.pvalue, 
                 A_YNG_vs_OLD.Symbols, A_YNG_vs_OLD.log2FC, A_YNG_vs_OLD.adj.pvalue
                 )) %>%
  
 gt(
    groupname_col = "Direction_w",
    rowname_col = "gene"
  ) %>%

  fmt_number(decimals = 2)  %>%
  
    cols_label(
    description = "Protein Description",
    H_EE_vs_SH.Symbols = "EE",
    A_YNG_vs_OLD.Symbols = "YNG",
    # adj.pvalue = "adj.p"
    ) %>%
  

  tab_style(
    style = list(
      cell_text(style = "italic",  size = px(12.5))
      ),
    locations = cells_stub()) %>%

    tab_options(table.font.size=11.5) %>%
    opt_vertical_padding(scale = 0.3) %>% # vert padding
  
  tab_spanner_delim( delim = ".",
                    split = "first", limit = 1) %>%


  tab_spanner(label = "Perez 2024 (Hip)",
              columns = c(mRNA_all, protein_all))  %>%


 #_________UP___________________________
  tab_style( # UP & ADJ P SIG!
    style = list(cell_fill(color = "#fccad8"),
                 cell_text(color = "#DA1884")),
    locations = list(
      cells_body(rows = mRNA_all == "\u2191 *",
                 columns = c(mRNA_all)), 
      cells_body(rows = protein_all == "\u2191 *",
                 columns = c(protein_all)),
      cells_body(rows =  H_EE_vs_SH.Symbols == "\u2191 *",
                 columns = c(H_EE_vs_SH.Symbols, H_EE_vs_SH.log2FC,
                             H_EE_vs_SH.adj.pvalue)),
      cells_body(rows =  A_YNG_vs_OLD.Symbols == "\u2191 *",
                 columns = c(A_YNG_vs_OLD.Symbols, A_YNG_vs_OLD.log2FC,
                             A_YNG_vs_OLD.adj.pvalue))
    )
  ) %>%
  
    tab_style( #_Up_adj.p_0.1
    style = list(cell_fill(color = "#fddde6"),
                 cell_text(color = "#d33682")),
    locations = list(
      cells_body(rows = mRNA_all == "\u2191 .",
                 columns = c(mRNA_all)), 
      cells_body(rows = protein_all == "\u2191 .",
                 columns = c(protein_all)),
      cells_body(rows =  H_EE_vs_SH.Symbols == "\u2191 .",
                 columns = c(H_EE_vs_SH.Symbols, H_EE_vs_SH.log2FC,
                             H_EE_vs_SH.adj.pvalue)),
      cells_body(rows =  A_YNG_vs_OLD.Symbols == "\u2191 .",
                 columns = c(A_YNG_vs_OLD.Symbols, A_YNG_vs_OLD.log2FC,
                             A_YNG_vs_OLD.adj.pvalue))
    )
  ) %>%
  
    tab_style( #_Up___non_sig_but_non_adjp_0.05ish
    style = list(cell_fill(color = "#FEEEF3"),
                 cell_text(color = "#d33682")),
    locations = list(
      cells_body(rows = mRNA_all == "\u2191",
                 columns = c(mRNA_all)), 
      cells_body(rows = protein_all == "\u2191",
                 columns = c(protein_all)),
      cells_body(
        rows =  H_EE_vs_SH.adj.pvalue > 0.11 & H_EE_vs_SH.adj.pvalue < 0.51 &  H_EE_vs_SH.log2FC > 0,
        columns = c(H_EE_vs_SH.Symbols, H_EE_vs_SH.log2FC,
                    H_EE_vs_SH.adj.pvalue)),
      cells_body(rows =  A_YNG_vs_OLD.adj.pvalue > 0.11 & A_YNG_vs_OLD.adj.pvalue < 0.51 & A_YNG_vs_OLD.log2FC > 0,
                 columns = c(A_YNG_vs_OLD.Symbols, A_YNG_vs_OLD.log2FC,
                             A_YNG_vs_OLD.adj.pvalue)))
  ) %>%
  
  
  tab_style( # 
    style = list(cell_text(color = "#d33682")),
    locations = list(
      cells_body(rows =  H_EE_vs_SH.adj.pvalue > 0.51 & H_EE_vs_SH.log2FC > 0.04,
        columns = c(H_EE_vs_SH.Symbols, H_EE_vs_SH.log2FC,
                    H_EE_vs_SH.adj.pvalue)),
  cells_body(rows = A_YNG_vs_OLD.adj.pvalue > 0.51 & A_YNG_vs_OLD.log2FC > 0.04,
                 columns = c(A_YNG_vs_OLD.Symbols, A_YNG_vs_OLD.log2FC,
                             A_YNG_vs_OLD.adj.pvalue))
    )
  ) %>%
  
  #_________UP___________________________
  tab_style( # Down & ADJ P SIG!
    style = list(cell_fill(color = "#C0DDF9"),
                 cell_text(color = "#0080FF")),
    locations = list(
      cells_body(rows = mRNA_all == "\u2193 *",
                 columns = c(mRNA_all)), 
      cells_body(rows = protein_all == "\u2193 *",
                 columns = c(protein_all)),
      cells_body(rows =  H_EE_vs_SH.Symbols == "\u2193 *",
                 columns = c(H_EE_vs_SH.Symbols, H_EE_vs_SH.log2FC,
                             H_EE_vs_SH.adj.pvalue)),
      cells_body(rows =  A_YNG_vs_OLD.Symbols == "\u2193 *",
                 columns = c(A_YNG_vs_OLD.Symbols, A_YNG_vs_OLD.log2FC,
                             A_YNG_vs_OLD.adj.pvalue))
    )
  ) %>%
  
      tab_style( #__Down_adj.p_0.1
    style = list(cell_fill(color = "#DBECFC"),
                 cell_text(color = "#2380c1")),
    locations = list(
      cells_body(rows = mRNA_all == "\u2193 .",
                 columns = c(mRNA_all)), 
      cells_body(rows = protein_all == "\u2193 .",
                 columns = c(protein_all)),
      cells_body(rows =  H_EE_vs_SH.Symbols == "\u2193 .",
                 columns = c(H_EE_vs_SH.Symbols, H_EE_vs_SH.log2FC,
                             H_EE_vs_SH.adj.pvalue)),
      cells_body(rows =  A_YNG_vs_OLD.Symbols == "\u2193 .",
                 columns = c(A_YNG_vs_OLD.Symbols, A_YNG_vs_OLD.log2FC,
                             A_YNG_vs_OLD.adj.pvalue))
    )
  ) %>%
  
  tab_style( #___Down__but__non_sigish
    style = list(cell_fill(color = "#EFF6FD"),
                 cell_text(color = "#2380c1")),
    locations = list(
       cells_body(rows = mRNA_all == "\u2193",
                 columns = c(mRNA_all)), 
      cells_body(rows = protein_all == "\u2193",
                 columns = c(protein_all)),
      cells_body(
        rows =  H_EE_vs_SH.adj.pvalue > 0.11 & H_EE_vs_SH.adj.pvalue < 0.51 &  H_EE_vs_SH.log2FC < 0,
        columns = c(H_EE_vs_SH.Symbols, H_EE_vs_SH.log2FC,
                    H_EE_vs_SH.adj.pvalue)),
      cells_body(rows =  A_YNG_vs_OLD.adj.pvalue > 0.11 & A_YNG_vs_OLD.adj.pvalue < 0.51 & A_YNG_vs_OLD.log2FC < 0,
                 columns = c(A_YNG_vs_OLD.Symbols, A_YNG_vs_OLD.log2FC,
                             A_YNG_vs_OLD.adj.pvalue)))
  ) %>%
  
  
  tab_style( #___Down__but_very_non_sig
    style = list(cell_text(color = "#2380c1")),
    locations = list(
      cells_body(rows =  H_EE_vs_SH.adj.pvalue > 0.51 & H_EE_vs_SH.log2FC < -0.04,
        columns = c(H_EE_vs_SH.Symbols, H_EE_vs_SH.log2FC,
                    H_EE_vs_SH.adj.pvalue)),
  cells_body(rows = A_YNG_vs_OLD.adj.pvalue > 0.51 & A_YNG_vs_OLD.log2FC < -0.04,
                 columns = c(A_YNG_vs_OLD.Symbols, A_YNG_vs_OLD.log2FC,
                             A_YNG_vs_OLD.adj.pvalue))
    )
  ) %>%
  
  #____NAs____Grey_out_NA_values________
    tab_style( # Down & ADJ P SIG!
    style = list(cell_text(color = "grey70", size = 9)),
    locations = list(
      cells_body(rows = is.na(description),
        columns = c(description, H_EE_vs_SH.Symbols,
                    H_EE_vs_SH.log2FC, H_EE_vs_SH.adj.pvalue, 
                    A_YNG_vs_OLD.Symbols, A_YNG_vs_OLD.log2FC,
                    A_YNG_vs_OLD.adj.pvalue)),
      cells_body(rows = is.na(protein_all),
        columns = c(protein_all))
    )
  )


print(perez_was_me_gt_2)
```

#### Best meth? - perez_was_me_3

```{r}

```
