---
title: "MSstatsTMT_2025_09_v3.1.4"
author: "Stephanie Huang"
date: "2025-09-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr) # read_tsv(), write_csv etc
library(dplyr) # %>% + other wrangling
library(stringr) # strings e.g. str_detect()
library(ggplot2) # plots 
library(paletteer) # color palette
library(tidyr) # pivot
library(VennDiagram)
```

-   **7.4 Reading data from multiple files -** <https://r4ds.hadley.nz/data-import.html#sec-readr-directory>

```{r}
# Individual .txt from 2025_09_sp_w_iso
# Using method from R4ds 2e (7.4) - simpler than before as no bind_rows is required.

mydir = 'input/2025_09_sp_w_iso_Steph_TMTpro_PSMs_MSstatsTMT_EEvsSH_for_PhD/txt_exports/'

PSMs_F1_8_files <- list.files(
  path = mydir, 
  pattern = ".*DEC2021_B1_TR1.*PSM.*\\.txt$", # DEC2021 1st then PSM 2nd & end .txt
  full.names = TRUE)

# Can also have pattern below if order varies
# pattern = ".*PSM.*DEC2021_B1_TR1_.*\\.txt$|.*DEC2021_B1_TR1_.*PSM.*\\.txt$",

PSMs_2025 <- read_tsv(PSMs_F1_8_files, id = "file_path")
```

-   filter with str_detect() - <https://r4ds.hadley.nz/regexps.html#sec-stringr-regex-funs>

```{r}
# 2024 mega PSMs from PD
df_2024 <- read_tsv("input/Steph_01NOV2024_all_EE-SH_M-F_MSstatsTMT/NOV2024_PSMs__Steph_TMTpro-16plex_all.txt",
                    id = "file_path")
  
colnames(df_2024)

# 
PSMs_2024 <- df_2024 %>%
  filter(str_detect(`Spectrum File`,  "DEC2021_B1_TR1"))
```

```{r}
# 2024 rrb (DEC2021_B1_TR1_F1-8 batch .pdresults - rrb_2025_09_11)
PSMs_2024_rrb <- read_tsv('input/Steph_01NOV2024_all_EE-SH_M-F_MSstatsTMT_2025_09_rr/txt_exports/Steph_TMTpro-16plex_DEC2021_B1_TR1_HpHF_F1-8_rrb_2025_09_11_PSMs.txt',
                          id = "file_path")
```

```{r}
# 2024 rro (DEC2021_B1_TR1_F1-8 individual .pdresults - rr0_2025_09_11)
mydir_rro = 'input/Steph_01NOV2024_all_EE-SH_M-F_MSstatsTMT_2025_09_rr/txt_exports/'

PSMs_rro_files <- list.files(path = mydir_rro,
                             pattern = ".*rro.*PSM.*\\.txt$",
                             full.names = TRUE)


PSMs_2024_rro <- read_tsv(PSMs_rro_files,
                          id = "file_path")
  

```

```{r}
# check it has the correct spectrum files.
unique(PSMs_2024$`Spectrum File`)
unique(PSMs_2025$`Spectrum File`)

dim(PSMs_2024) # 73250 x 54
dim(PSMs_2025) # 77233 x 54
```

```{r}
summary(PSMs_2024)
summary(PSMs_2025)
```

```{r}
# length(unique(PSMs_2024$`Annotated Sequence`)) #33688
# length(unique(PSMs_2024_rrb$`Annotated Sequence`)) #34781
# length(unique(PSMs_2024_rro$`Annotated Sequence`)) #36268
# length(unique(PSMs_2025$`Annotated Sequence`)) #36343
# 
# length(unique(PSMs_2024$`Protein Accessions`)) #4238
# length(unique(PSMs_2024_rrb$`Protein Accessions`)) #4393
# length(unique(PSMs_2024_rro$`Protein Accessions`)) #4565
# length(unique(PSMs_2025$`Protein Accessions`)) #4554
# 
# length(unique(PSMs_2024$`Master Protein Accessions`)) #3808
# length(unique(PSMs_2024_rrb$`Master Protein Accessions`)) #3844
# length(unique(PSMs_2024_rro$`Master Protein Accessions`)) #4058
# length(unique(PSMs_2025$`Master Protein Accessions`)) #4045
```

Part 2

-   <https://stats.oarc.ucla.edu/r/faq/how-can-i-generate-a-venn-diagram-in-r/>

Make combined df. Get unique sequences in each df. then do venn diagram

```{r}
#https://dplyr.tidyverse.org/reference/bind_rows.html
# bind_rows() .id alone doesn't work (just gives 1,2,3,4). need list & var name = df
cPSMs <- bind_rows(list(PSMs_2024 = PSMs_2024, 
                        PSMs_2024_rrb = PSMs_2024_rrb, 
                        PSMs_2024_rro = PSMs_2024_rro, 
                        PSMs_2025 = PSMs_2025),
                   .id = "df_id")
```

cPSMs_u_aseq

```{r}
# https://dplyr.tidyverse.org/reference/distinct.html
# get distinct/unique annotated sequences by df group
cPSMs_u_aseq <- cPSMs %>%
  group_by(df_id) %>%
  distinct(`Annotated Sequence`) 

# dim(cPSMs_u_aseq) # 141080 x 2
# length(unique(cPSMs_u_aseq$`Annotated Sequence`)) # 37343
```

```{r fig.height=4, fig.width=8}
# https://r-charts.com/color-palettes/
# https://r-graph-gallery.com/package/paletteer.html
# plot no. of unique annotated seqeunces per df/group
cPSMs_u_aseq_plot <- cPSMs_u_aseq %>%
  group_by(df_id) %>%
  tally() %>%  # get tally of unique sequences by df for plot
  ggplot(aes(x = df_id, y = n, fill = df_id)) +
  geom_col(width = 0.6, color = "grey10", alpha = .7) + 
  ylim(0,40000) + 
  geom_text(aes(label = paste0(n)), # annotate count on graph
            vjust = -.2) +
  scale_fill_paletteer_d("ggthemes::excel_Organic") +
  labs(x = "PSM dataframe set (different PD analysis)",
       y = "no. of unique annotated sequences (n)",
       title = "Count of distinct annotated sequences in each PD PSM set (df_id)",
       subtitle = "Analysing as batch drops the no. of unique annotated sequences!",
       caption = "Each set has the SAME 8 LC-MS files! These are DEC2021_B1_TR1_F1-8.\n 
       PSMs_2024, PSMs_2024_rrb & PSMs_2024_rro all use the SAME FASTA & PD method! \n         The ONLY DIFFERENCE is that PSMs_2024 was analysed as batch (96 files submitted),
       PSMs_2024_rrb was analysed as batch (8 files submitted), while PSMs_2024_rro was submitted one by one (not as batch). \n 
       PSMs_2025 also submitted files one by one like PSMs_2024_rro & used the same PD method, but had a slightly newer SwissProt db (23 more seq).\n
       The mild increase between PSMs_2025 & PSMs_2024_rro of 75 seems reasonable for increasing the FASTA db by 23 sequences.
       However, the change between the other 3 based on running individually or by batch is bizzare. 
       The LC-MS raw files were input as files not fractions in PD & the PSMs table from PD shows PSMs by separate LCMS runs. So it should not be grouping it!
       Also the PD userguide does not indicate grouping PSMs (it groups at the peptide & protein grouping level!)
       Also the bizzare thing is that changing the no. of files submitted changes the no. of PSMs observed!?!?!?! WHY? Could it be their weird ") +
  theme_bw() + 
  theme(legend.position = "bottom")


plot(cPSMs_u_aseq_plot)
```

Venn diagram

```{r}
# https://r-graph-gallery.com/14-venn-diagramm

```
